#!/usr/bin/env python3
"""
MK64 Stage 2: emit adpcm_pool.bin + generated-C descriptor table.
Reuses transcode.py (decode -> Yamaha ADPCM encode -> 2x oversize trick).

Lookup key = sampleAddr (offset into the shared audiotables blob). Runtime
derives it as (patched sample->sampleAddr - (audiotablesBase + 0xB0)).
"""

from pathlib import Path

from mk64_albank_parse import parse_all
from transcode import transcode_sample

ALIGN = 32


def align_up(n, a):
    return (n + a - 1) & ~(a - 1)


def main(audiobanks, audiotables, outdir, incdir, pool_path):
    outdir = Path(outdir)
    incdir = Path(incdir)
    pool_path = Path(pool_path)
    tbl_base, samples = parse_all(audiobanks, audiotables, with_data=True)

    descs = []
    blob = bytearray()
    for s in samples.values():
        d = transcode_sample(s)
        d["pool_offset"] = len(blob)
        blob += d["adpcm"]
        blob += b"\x00" * (align_up(len(blob), ALIGN) - len(blob))
        d["key"] = s.addr
        descs.append(d)

    descs.sort(key=lambda d: d["key"])

    # integrity
    keys = [d["key"] for d in descs]
    assert keys == sorted(keys) and len(keys) == len(set(keys))
    for d in descs:
        assert blob[d["pool_offset"]:d["pool_offset"] + len(d["adpcm"])] == d["adpcm"]
        assert d["nsamples"] <= 65534
        assert 0 <= d["loop_start"] <= d["loop_end"] <= d["nsamples"]

    outdir.mkdir(parents=True, exist_ok=True)
    incdir.mkdir(parents=True, exist_ok=True)
    pool_path.parent.mkdir(parents=True, exist_ok=True)
    pool_path.write_bytes(blob)

    h = ["/* Auto-generated by tools/aica/mk64_emit.py. Do not edit. */",
         "#ifndef AICA_SAMPLE_TABLE_H", "#define AICA_SAMPLE_TABLE_H", "#include <stdint.h>", "",
         "typedef struct {",
         "    uint32_t src_offset;       /* sampleAddr offset into shared audiotables blob (key) */",
         "    uint32_t pool_offset;      /* byte offset into adpcm_pool.bin */",
         "    uint32_t byte_len;",
         "    uint16_t nsamples;",
         "    uint16_t loop_start;",
         "    uint16_t loop_end;",
         "    uint8_t  loop_flag;",
         "    uint8_t  downsample_shift;",
         "} AicaSampleDesc;", "",
         f"#define AICA_SAMPLE_COUNT {len(descs)}",
         f"#define AICA_ADPCM_POOL_SIZE {len(blob)}u",
         "extern const AicaSampleDesc gAicaSampleTable[AICA_SAMPLE_COUNT];", "", "#endif"]
    (incdir / "aica_sample_table.h").write_text("\n".join(h) + "\n")

    c = ["/* Auto-generated by tools/aica/mk64_emit.py. Do not edit. */",
         '#include "aica_sample_table.h"', "",
         "const AicaSampleDesc gAicaSampleTable[AICA_SAMPLE_COUNT] = {"]
    for d in descs:
        c.append(f"    {{ 0x{d['key']:06X}, 0x{d['pool_offset']:06X}, {len(d['adpcm']):>6}, "
                 f"{d['nsamples']:>5}, {d['loop_start']:>5}, {d['loop_end']:>5}, "
                 f"{1 if d['loop'] else 0}, {d['downsample_shift']} }},")
    c.append("};")
    (outdir / "aica_sample_table.c").write_text("\n".join(c) + "\n")

    from transcode import _HAVE_SCIPY
    print(f"mk64_emit: {len(descs)} descs, pool {len(blob):,} B -> {pool_path}, "
          f"table -> {outdir}/{incdir}{'' if _HAVE_SCIPY else '  [stdlib decimate fallback]'}")


if __name__ == "__main__":
    import argparse
    ap = argparse.ArgumentParser()
    ap.add_argument("--audiobanks", required=True)
    ap.add_argument("--audiotables", required=True)
    ap.add_argument("--outdir", required=True, help="dir for aica_sample_table.c")
    ap.add_argument("--incdir", help="dir for aica_sample_table.h (default: outdir)")
    ap.add_argument("--pool", required=True, help="output path for adpcm_pool.bin")
    a = ap.parse_args()
    main(a.audiobanks, a.audiotables, a.outdir, a.incdir or a.outdir, a.pool)
