! Mario Kart 64 (U) disassembly and split file
! generated by n64split v0.4a - N64 ROM splitter

.include "macros.inc"

.section .data
glabel __audio_tablesSegmentStart
glabel __audio_tablesSegmentRomStart
.incbin "bin/audiotables.bin" ! Audiotables and data
glabel __audio_tablesSegmentEnd
glabel __audio_tablesSegmentRomEnd

