# Mario Kart 64 (U) disassembly and split file
# generated by n64split v0.4a - N64 ROM splitter

.include "macros.inc"

.section .data
glabel __sequencesSegmentStart
glabel __sequencesSegmentRomStart
# music sequence table
glabel _music_sequence_table_header
# this should be 30...
.hword 3, ((_music_sequence_table_end - _music_sequence_table) / 8) - 1 
glabel _music_sequence_table
.long (_seq_00 - _music_sequence_table_header), (_seq_00_end - _seq_00) # 0x00100, 0x2830
.long (_seq_01 - _music_sequence_table_header), (_seq_01_end - _seq_01) # 0x02930, 0x1B30
.long (_seq_02 - _music_sequence_table_header), (_seq_02_end - _seq_02) # 0x04460, 0x0D60
.long (_seq_03 - _music_sequence_table_header), (_seq_03_end - _seq_03) # 0x051C0, 0x1A10
.long (_seq_04 - _music_sequence_table_header), (_seq_04_end - _seq_04) # 0x06BD0, 0x1CA0
.long (_seq_05 - _music_sequence_table_header), (_seq_05_end - _seq_05) # 0x08870, 0x1F70
.long (_seq_06 - _music_sequence_table_header), (_seq_06_end - _seq_06) # 0x0A7E0, 0x1EE0
.long (_seq_07 - _music_sequence_table_header), (_seq_07_end - _seq_07) # 0x0C6C0, 0x16D0
.long (_seq_08 - _music_sequence_table_header), (_seq_08_end - _seq_08) # 0x0DD90, 0x23D0
.long (_seq_09 - _music_sequence_table_header), (_seq_09_end - _seq_09) # 0x10160, 0x1800
.long (_seq_0A - _music_sequence_table_header), (_seq_0A_end - _seq_0A) # 0x11960, 0x1AE0
.long (_seq_0B - _music_sequence_table_header), (_seq_0B_end - _seq_0B) # 0x13440, 0x05F0
.long (_seq_0C - _music_sequence_table_header), (_seq_0C_end - _seq_0C) # 0x13A30, 0x03D0
.long (_seq_0D - _music_sequence_table_header), (_seq_0D_end - _seq_0D) # 0x13E00, 0x0360
.long (_seq_0E - _music_sequence_table_header), (_seq_0E_end - _seq_0E) # 0x14160, 0x02E0
.long (_seq_0F - _music_sequence_table_header), (_seq_0F_end - _seq_0F) # 0x14440, 0x04C0
.long (_seq_10 - _music_sequence_table_header), (_seq_10_end - _seq_10) # 0x14900, 0x1410
.long (_seq_11 - _music_sequence_table_header), (_seq_11_end - _seq_11) # 0x15D10, 0x06E0
.long (_seq_12 - _music_sequence_table_header), (_seq_12_end - _seq_12) # 0x163F0, 0x32F0
.long (_seq_13 - _music_sequence_table_header), (_seq_13_end - _seq_13) # 0x196E0, 0x06C0
.long (_seq_14 - _music_sequence_table_header), (_seq_14_end - _seq_14) # 0x19DA0, 0x04B0
.long (_seq_15 - _music_sequence_table_header), (_seq_15_end - _seq_15) # 0x1A250, 0x1160
.long (_seq_16 - _music_sequence_table_header), (_seq_16_end - _seq_16) # 0x1B3B0, 0x0310
.long (_seq_17 - _music_sequence_table_header), (_seq_17_end - _seq_17) # 0x1B6C0, 0x12B0
.long (_seq_18 - _music_sequence_table_header), (_seq_18_end - _seq_18) # 0x1C970, 0x0600
.long (_seq_19 - _music_sequence_table_header), (_seq_19_end - _seq_19) # 0x1CF70, 0x16E0
.long (_seq_1A - _music_sequence_table_header), (_seq_1A_end - _seq_1A) # 0x1E650, 0x0AD0
.long (_seq_1B - _music_sequence_table_header), (_seq_1B_end - _seq_1B) # 0x1F120, 0x0C80
.long (_seq_1C - _music_sequence_table_header), (_seq_1C_end - _seq_1C) # 0x1FDA0, 0x2750
.long (_seq_1D - _music_sequence_table_header), (_seq_1D_end - _seq_1D) # 0x224F0, 0x0C80
glabel _music_sequence_table_end

.align 4, 0x00

glabel _seq_00
.incbin "music/00_seq_00.m64"
glabel _seq_00_end

glabel _seq_01
.incbin "music/01_title_screen.m64"
glabel _seq_01_end

glabel _seq_02
.incbin "music/02_main_menu.m64"
glabel _seq_02_end

glabel _seq_03
.incbin "music/03_racways_wario_stadium.m64"
glabel _seq_03_end

glabel _seq_04
.incbin "music/04_moo_moo_fame_yoshi_valley.m64"
glabel _seq_04_end

glabel _seq_05
.incbin "music/05_choco_mountain.m64"
glabel _seq_05_end

glabel _seq_06
.incbin "music/06_koopa_troopa_beach.m64"
glabel _seq_06_end

glabel _seq_07
.incbin "music/07_banshee_boardwalk.m64"
glabel _seq_07_end

glabel _seq_08
.incbin "music/08_seq_08.m64"
glabel _seq_08_end

glabel _seq_09
.incbin "music/09_seq_09.m64"
glabel _seq_09_end

glabel _seq_0A
.incbin "music/10_kalimari_desert.m64"
glabel _seq_0A_end

glabel _seq_0B
.incbin "music/11_start_grid_gp_vs.m64"
glabel _seq_0B_end

glabel _seq_0C
.incbin "music/12_final_lap_fanfare.m64"
glabel _seq_0C_end

glabel _seq_0D
.incbin "music/13_finish_1st_place.m64"
glabel _seq_0D_end

glabel _seq_0E
.incbin "music/14_finish_2nd_4th_place.m64"
glabel _seq_0E_end

glabel _seq_0F
.incbin "music/15_finish_5th_8th_place.m64"
glabel _seq_0F_end

glabel _seq_10
.incbin "music/16_seq_10.m64"
glabel _seq_10_end

glabel _seq_11
.incbin "music/17_star_jingle.m64"
glabel _seq_11_end

glabel _seq_12
.incbin "music/18_rainbow_road.m64"
glabel _seq_12_end

glabel _seq_13
.incbin "music/19_maybe_boo_item.m64"
glabel _seq_13_end

glabel _seq_14
.incbin "music/20_game_over.m64"
glabel _seq_14_end

glabel _seq_15
.incbin "music/21_toads_turnpike.m64"
glabel _seq_15_end

glabel _seq_16
.incbin "music/22_start_gird_time_attack.m64"
glabel _seq_16_end

glabel _seq_17
.incbin "music/23_vs_battle_results.m64"
glabel _seq_17_end

glabel _seq_18
.incbin "music/24_losing_results.m64"
glabel _seq_18_end

glabel _seq_19
.incbin "music/25_battle_arenas.m64"
glabel _seq_19_end

glabel _seq_1A
.incbin "music/26_award_ceremony_buildup.m64"
glabel _seq_1A_end

glabel _seq_1B
.incbin "music/27_award_ceremony_1st_3rd.m64"
glabel _seq_1B_end

glabel _seq_1C
.incbin "music/28_staff_roll.m64"
glabel _seq_1C_end

glabel _seq_1D
.incbin "music/29_award_ceremony_4th_8th.m64"
glabel _seq_1D_end
glabel __sequencesSegmentEnd
glabel __sequencesSegmentRomEnd

