# Mario Kart 64 (U) disassembly and split file
# generated by n64split v0.4a - N64 ROM splitter

.include "macros.inc"

.data

# segment 0x0A000000 (0x729A30 - 0x7E684F)

.align 2, 0x00
glabel _gTextureMarioFace00
.incbin "assets/character_select/mario/mario_face_00.mio0"
glabel _gTextureMarioFace00_end

.align 2, 0x00
glabel _gTextureMarioFace01
.incbin "assets/character_select/mario/mario_face_01.mio0"
glabel _gTextureMarioFace01_end

.align 2, 0x00
glabel _gTextureMarioFace02
.incbin "assets/character_select/mario/mario_face_02.mio0"
glabel _gTextureMarioFace02_end

.align 2, 0x00
glabel _gTextureMarioFace03
.incbin "assets/character_select/mario/mario_face_03.mio0"
glabel _gTextureMarioFace03_end

.align 2, 0x00
glabel _gTextureMarioFace04
.incbin "assets/character_select/mario/mario_face_04.mio0"
glabel _gTextureMarioFace04_end

.align 2, 0x00
glabel _gTextureMarioFace05
.incbin "assets/character_select/mario/mario_face_05.mio0"
glabel _gTextureMarioFace05_end

.align 2, 0x00
glabel _gTextureMarioFace06
.incbin "assets/character_select/mario/mario_face_06.mio0"
glabel _gTextureMarioFace06_end

.align 2, 0x00
glabel _gTextureMarioFace07
.incbin "assets/character_select/mario/mario_face_07.mio0"
glabel _gTextureMarioFace07_end

.align 2, 0x00
glabel _gTextureMarioFace08
.incbin "assets/character_select/mario/mario_face_08.mio0"
glabel _gTextureMarioFace08_end

.align 2, 0x00
glabel _gTextureMarioFace09
.incbin "assets/character_select/mario/mario_face_09.mio0"
glabel _gTextureMarioFace09_end

.align 2, 0x00
glabel _gTextureMarioFace10
.incbin "assets/character_select/mario/mario_face_10.mio0"
glabel _gTextureMarioFace10_end

.align 2, 0x00
glabel _gTextureMarioFace11
.incbin "assets/character_select/mario/mario_face_11.mio0"
glabel _gTextureMarioFace11_end

.align 2, 0x00
glabel _gTextureMarioFace12
.incbin "assets/character_select/mario/mario_face_12.mio0"
glabel _gTextureMarioFace12_end

.align 2, 0x00
glabel _gTextureMarioFace13
.incbin "assets/character_select/mario/mario_face_13.mio0"
glabel _gTextureMarioFace13_end

.align 2, 0x00
glabel _gTextureMarioFace14
.incbin "assets/character_select/mario/mario_face_14.mio0"
glabel _gTextureMarioFace14_end

.align 2, 0x00
glabel _gTextureMarioFace15
.incbin "assets/character_select/mario/mario_face_15.mio0"
glabel _gTextureMarioFace15_end

.align 2, 0x00
glabel _gTextureMarioFace16
.incbin "assets/character_select/mario/mario_face_16.mio0"
glabel _gTextureMarioFace16_end

.align 2, 0x00
glabel _gTextureLuigiFace00
.incbin "assets/character_select/luigi/luigi_face_00.mio0"
glabel _gTextureLuigiFace00_end

.align 2, 0x00
glabel _gTextureLuigiFace01
.incbin "assets/character_select/luigi/luigi_face_01.mio0"
glabel _gTextureLuigiFace01_end

.align 2, 0x00
glabel _gTextureLuigiFace02
.incbin "assets/character_select/luigi/luigi_face_02.mio0"
glabel _gTextureLuigiFace02_end

.align 2, 0x00
glabel _gTextureLuigiFace03
.incbin "assets/character_select/luigi/luigi_face_03.mio0"
glabel _gTextureLuigiFace03_end

.align 2, 0x00
glabel _gTextureLuigiFace04
.incbin "assets/character_select/luigi/luigi_face_04.mio0"
glabel _gTextureLuigiFace04_end

.align 2, 0x00
glabel _gTextureLuigiFace05
.incbin "assets/character_select/luigi/luigi_face_05.mio0"
glabel _gTextureLuigiFace05_end

.align 2, 0x00
glabel _gTextureLuigiFace06
.incbin "assets/character_select/luigi/luigi_face_06.mio0"
glabel _gTextureLuigiFace06_end

.align 2, 0x00
glabel _gTextureLuigiFace07
.incbin "assets/character_select/luigi/luigi_face_07.mio0"
glabel _gTextureLuigiFace07_end

.align 2, 0x00
glabel _gTextureLuigiFace08
.incbin "assets/character_select/luigi/luigi_face_08.mio0"
glabel _gTextureLuigiFace08_end

.align 2, 0x00
glabel _gTextureLuigiFace09
.incbin "assets/character_select/luigi/luigi_face_09.mio0"
glabel _gTextureLuigiFace09_end

.align 2, 0x00
glabel _gTextureLuigiFace10
.incbin "assets/character_select/luigi/luigi_face_10.mio0"
glabel _gTextureLuigiFace10_end

.align 2, 0x00
glabel _gTextureLuigiFace11
.incbin "assets/character_select/luigi/luigi_face_11.mio0"
glabel _gTextureLuigiFace11_end

.align 2, 0x00
glabel _gTextureLuigiFace12
.incbin "assets/character_select/luigi/luigi_face_12.mio0"
glabel _gTextureLuigiFace12_end

.align 2, 0x00
glabel _gTextureLuigiFace13
.incbin "assets/character_select/luigi/luigi_face_13.mio0"
glabel _gTextureLuigiFace13_end

.align 2, 0x00
glabel _gTextureLuigiFace14
.incbin "assets/character_select/luigi/luigi_face_14.mio0"
glabel _gTextureLuigiFace14_end

.align 2, 0x00
glabel _gTextureLuigiFace15
.incbin "assets/character_select/luigi/luigi_face_15.mio0"
glabel _gTextureLuigiFace15_end

.align 2, 0x00
glabel _gTextureLuigiFace16
.incbin "assets/character_select/luigi/luigi_face_16.mio0"
glabel _gTextureLuigiFace16_end

.align 2, 0x00
glabel _gTexturePeachFace00
.incbin "assets/character_select/peach/peach_face_00.mio0"
glabel _gTexturePeachFace00_end

.align 2, 0x00
glabel _gTexturePeachFace01
.incbin "assets/character_select/peach/peach_face_01.mio0"
glabel _gTexturePeachFace01_end

.align 2, 0x00
glabel _gTexturePeachFace02
.incbin "assets/character_select/peach/peach_face_02.mio0"
glabel _gTexturePeachFace02_end

.align 2, 0x00
glabel _gTexturePeachFace03
.incbin "assets/character_select/peach/peach_face_03.mio0"
glabel _gTexturePeachFace03_end

.align 2, 0x00
glabel _gTexturePeachFace04
.incbin "assets/character_select/peach/peach_face_04.mio0"
glabel _gTexturePeachFace04_end

.align 2, 0x00
glabel _gTexturePeachFace05
.incbin "assets/character_select/peach/peach_face_05.mio0"
glabel _gTexturePeachFace05_end

.align 2, 0x00
glabel _gTexturePeachFace06
.incbin "assets/character_select/peach/peach_face_06.mio0"
glabel _gTexturePeachFace06_end

.align 2, 0x00
glabel _gTexturePeachFace07
.incbin "assets/character_select/peach/peach_face_07.mio0"
glabel _gTexturePeachFace07_end

.align 2, 0x00
glabel _gTexturePeachFace08
.incbin "assets/character_select/peach/peach_face_08.mio0"
glabel _gTexturePeachFace08_end

.align 2, 0x00
glabel _gTexturePeachFace09
.incbin "assets/character_select/peach/peach_face_09.mio0"
glabel _gTexturePeachFace09_end

.align 2, 0x00
glabel _gTexturePeachFace10
.incbin "assets/character_select/peach/peach_face_10.mio0"
glabel _gTexturePeachFace10_end

.align 2, 0x00
glabel _gTexturePeachFace11
.incbin "assets/character_select/peach/peach_face_11.mio0"
glabel _gTexturePeachFace11_end

.align 2, 0x00
glabel _gTexturePeachFace12
.incbin "assets/character_select/peach/peach_face_12.mio0"
glabel _gTexturePeachFace12_end

.align 2, 0x00
glabel _gTexturePeachFace13
.incbin "assets/character_select/peach/peach_face_13.mio0"
glabel _gTexturePeachFace13_end

.align 2, 0x00
glabel _gTexturePeachFace14
.incbin "assets/character_select/peach/peach_face_14.mio0"
glabel _gTexturePeachFace14_end

.align 2, 0x00
glabel _gTexturePeachFace15
.incbin "assets/character_select/peach/peach_face_15.mio0"
glabel _gTexturePeachFace15_end

.align 2, 0x00
glabel _gTexturePeachFace16
.incbin "assets/character_select/peach/peach_face_16.mio0"
glabel _gTexturePeachFace16_end

.align 2, 0x00
glabel _gTextureToadFace00
.incbin "assets/character_select/toad/toad_face_00.mio0"
glabel _gTextureToadFace00_end

.align 2, 0x00
glabel _gTextureToadFace01
.incbin "assets/character_select/toad/toad_face_01.mio0"
glabel _gTextureToadFace01_end

.align 2, 0x00
glabel _gTextureToadFace02
.incbin "assets/character_select/toad/toad_face_02.mio0"
glabel _gTextureToadFace02_end

.align 2, 0x00
glabel _gTextureToadFace03
.incbin "assets/character_select/toad/toad_face_03.mio0"
glabel _gTextureToadFace03_end

.align 2, 0x00
glabel _gTextureToadFace04
.incbin "assets/character_select/toad/toad_face_04.mio0"
glabel _gTextureToadFace04_end

.align 2, 0x00
glabel _gTextureToadFace05
.incbin "assets/character_select/toad/toad_face_05.mio0"
glabel _gTextureToadFace05_end

.align 2, 0x00
glabel _gTextureToadFace06
.incbin "assets/character_select/toad/toad_face_06.mio0"
glabel _gTextureToadFace06_end

.align 2, 0x00
glabel _gTextureToadFace07
.incbin "assets/character_select/toad/toad_face_07.mio0"
glabel _gTextureToadFace07_end

.align 2, 0x00
glabel _gTextureToadFace08
.incbin "assets/character_select/toad/toad_face_08.mio0"
glabel _gTextureToadFace08_end

.align 2, 0x00
glabel _gTextureToadFace09
.incbin "assets/character_select/toad/toad_face_09.mio0"
glabel _gTextureToadFace09_end

.align 2, 0x00
glabel _gTextureToadFace10
.incbin "assets/character_select/toad/toad_face_10.mio0"
glabel _gTextureToadFace10_end

.align 2, 0x00
glabel _gTextureToadFace11
.incbin "assets/character_select/toad/toad_face_11.mio0"
glabel _gTextureToadFace11_end

.align 2, 0x00
glabel _gTextureToadFace12
.incbin "assets/character_select/toad/toad_face_12.mio0"
glabel _gTextureToadFace12_end

.align 2, 0x00
glabel _gTextureToadFace13
.incbin "assets/character_select/toad/toad_face_13.mio0"
glabel _gTextureToadFace13_end

.align 2, 0x00
glabel _gTextureToadFace14
.incbin "assets/character_select/toad/toad_face_14.mio0"
glabel _gTextureToadFace14_end

.align 2, 0x00
glabel _gTextureToadFace15
.incbin "assets/character_select/toad/toad_face_15.mio0"
glabel _gTextureToadFace15_end

.align 2, 0x00
glabel _gTextureToadFace16
.incbin "assets/character_select/toad/toad_face_16.mio0"
glabel _gTextureToadFace16_end

.align 2, 0x00
glabel _gTextureYoshiFace00
.incbin "assets/character_select/yoshi/yoshi_face_00.mio0"
glabel _gTextureYoshiFace00_end

.align 2, 0x00
glabel _gTextureYoshiFace01
.incbin "assets/character_select/yoshi/yoshi_face_01.mio0"
glabel _gTextureYoshiFace01_end

.align 2, 0x00
glabel _gTextureYoshiFace02
.incbin "assets/character_select/yoshi/yoshi_face_02.mio0"
glabel _gTextureYoshiFace02_end

.align 2, 0x00
glabel _gTextureYoshiFace03
.incbin "assets/character_select/yoshi/yoshi_face_03.mio0"
glabel _gTextureYoshiFace03_end

.align 2, 0x00
glabel _gTextureYoshiFace04
.incbin "assets/character_select/yoshi/yoshi_face_04.mio0"
glabel _gTextureYoshiFace04_end

.align 2, 0x00
glabel _gTextureYoshiFace05
.incbin "assets/character_select/yoshi/yoshi_face_05.mio0"
glabel _gTextureYoshiFace05_end

.align 2, 0x00
glabel _gTextureYoshiFace06
.incbin "assets/character_select/yoshi/yoshi_face_06.mio0"
glabel _gTextureYoshiFace06_end

.align 2, 0x00
glabel _gTextureYoshiFace07
.incbin "assets/character_select/yoshi/yoshi_face_07.mio0"
glabel _gTextureYoshiFace07_end

.align 2, 0x00
glabel _gTextureYoshiFace08
.incbin "assets/character_select/yoshi/yoshi_face_08.mio0"
glabel _gTextureYoshiFace08_end

.align 2, 0x00
glabel _gTextureYoshiFace09
.incbin "assets/character_select/yoshi/yoshi_face_09.mio0"
glabel _gTextureYoshiFace09_end

.align 2, 0x00
glabel _gTextureYoshiFace10
.incbin "assets/character_select/yoshi/yoshi_face_10.mio0"
glabel _gTextureYoshiFace10_end

.align 2, 0x00
glabel _gTextureYoshiFace11
.incbin "assets/character_select/yoshi/yoshi_face_11.mio0"
glabel _gTextureYoshiFace11_end

.align 2, 0x00
glabel _gTextureYoshiFace12
.incbin "assets/character_select/yoshi/yoshi_face_12.mio0"
glabel _gTextureYoshiFace12_end

.align 2, 0x00
glabel _gTextureYoshiFace13
.incbin "assets/character_select/yoshi/yoshi_face_13.mio0"
glabel _gTextureYoshiFace13_end

.align 2, 0x00
glabel _gTextureYoshiFace14
.incbin "assets/character_select/yoshi/yoshi_face_14.mio0"
glabel _gTextureYoshiFace14_end

.align 2, 0x00
glabel _gTextureYoshiFace15
.incbin "assets/character_select/yoshi/yoshi_face_15.mio0"
glabel _gTextureYoshiFace15_end

.align 2, 0x00
glabel _gTextureYoshiFace16
.incbin "assets/character_select/yoshi/yoshi_face_16.mio0"
glabel _gTextureYoshiFace16_end

.align 2, 0x00
glabel _gTextureDkFace00
.incbin "assets/character_select/donkeykong/donkeykong_face_00.mio0"
glabel _gTextureDkFace00_end

.align 2, 0x00
glabel _gTextureDkFace01
.incbin "assets/character_select/donkeykong/donkeykong_face_01.mio0"
glabel _gTextureDkFace01_end

.align 2, 0x00
glabel _gTextureDkFace02
.incbin "assets/character_select/donkeykong/donkeykong_face_02.mio0"
glabel _gTextureDkFace02_end

.align 2, 0x00
glabel _gTextureDkFace03
.incbin "assets/character_select/donkeykong/donkeykong_face_03.mio0"
glabel _gTextureDkFace03_end

.align 2, 0x00
glabel _gTextureDkFace04
.incbin "assets/character_select/donkeykong/donkeykong_face_04.mio0"
glabel _gTextureDkFace04_end

.align 2, 0x00
glabel _gTextureDkFace05
.incbin "assets/character_select/donkeykong/donkeykong_face_05.mio0"
glabel _gTextureDkFace05_end

.align 2, 0x00
glabel _gTextureDkFace06
.incbin "assets/character_select/donkeykong/donkeykong_face_06.mio0"
glabel _gTextureDkFace06_end

.align 2, 0x00
glabel _gTextureDkFace07
.incbin "assets/character_select/donkeykong/donkeykong_face_07.mio0"
glabel _gTextureDkFace07_end

.align 2, 0x00
glabel _gTextureDkFace08
.incbin "assets/character_select/donkeykong/donkeykong_face_08.mio0"
glabel _gTextureDkFace08_end

.align 2, 0x00
glabel _gTextureDkFace09
.incbin "assets/character_select/donkeykong/donkeykong_face_09.mio0"
glabel _gTextureDkFace09_end

.align 2, 0x00
glabel _gTextureDkFace10
.incbin "assets/character_select/donkeykong/donkeykong_face_10.mio0"
glabel _gTextureDkFace10_end

.align 2, 0x00
glabel _gTextureDkFace11
.incbin "assets/character_select/donkeykong/donkeykong_face_11.mio0"
glabel _gTextureDkFace11_end

.align 2, 0x00
glabel _gTextureDkFace12
.incbin "assets/character_select/donkeykong/donkeykong_face_12.mio0"
glabel _gTextureDkFace12_end

.align 2, 0x00
glabel _gTextureDkFace13
.incbin "assets/character_select/donkeykong/donkeykong_face_13.mio0"
glabel _gTextureDkFace13_end

.align 2, 0x00
glabel _gTextureDkFace14
.incbin "assets/character_select/donkeykong/donkeykong_face_14.mio0"
glabel _gTextureDkFace14_end

.align 2, 0x00
glabel _gTextureDkFace15
.incbin "assets/character_select/donkeykong/donkeykong_face_15.mio0"
glabel _gTextureDkFace15_end

.align 2, 0x00
glabel _gTextureDkFace16
.incbin "assets/character_select/donkeykong/donkeykong_face_16.mio0"
glabel _gTextureDkFace16_end

.align 2, 0x00
glabel _gTextureWarioFace00
.incbin "assets/character_select/wario/wario_face_00.mio0"
glabel _gTextureWarioFace00_end

.align 2, 0x00
glabel _gTextureWarioFace01
.incbin "assets/character_select/wario/wario_face_01.mio0"
glabel _gTextureWarioFace01_end

.align 2, 0x00
glabel _gTextureWarioFace02
.incbin "assets/character_select/wario/wario_face_02.mio0"
glabel _gTextureWarioFace02_end

.align 2, 0x00
glabel _gTextureWarioFace03
.incbin "assets/character_select/wario/wario_face_03.mio0"
glabel _gTextureWarioFace03_end

.align 2, 0x00
glabel _gTextureWarioFace04
.incbin "assets/character_select/wario/wario_face_04.mio0"
glabel _gTextureWarioFace04_end

.align 2, 0x00
glabel _gTextureWarioFace05
.incbin "assets/character_select/wario/wario_face_05.mio0"
glabel _gTextureWarioFace05_end

.align 2, 0x00
glabel _gTextureWarioFace06
.incbin "assets/character_select/wario/wario_face_06.mio0"
glabel _gTextureWarioFace06_end

.align 2, 0x00
glabel _gTextureWarioFace07
.incbin "assets/character_select/wario/wario_face_07.mio0"
glabel _gTextureWarioFace07_end

.align 2, 0x00
glabel _gTextureWarioFace08
.incbin "assets/character_select/wario/wario_face_08.mio0"
glabel _gTextureWarioFace08_end

.align 2, 0x00
glabel _gTextureWarioFace09
.incbin "assets/character_select/wario/wario_face_09.mio0"
glabel _gTextureWarioFace09_end

.align 2, 0x00
glabel _gTextureWarioFace10
.incbin "assets/character_select/wario/wario_face_10.mio0"
glabel _gTextureWarioFace10_end

.align 2, 0x00
glabel _gTextureWarioFace11
.incbin "assets/character_select/wario/wario_face_11.mio0"
glabel _gTextureWarioFace11_end

.align 2, 0x00
glabel _gTextureWarioFace12
.incbin "assets/character_select/wario/wario_face_12.mio0"
glabel _gTextureWarioFace12_end

.align 2, 0x00
glabel _gTextureWarioFace13
.incbin "assets/character_select/wario/wario_face_13.mio0"
glabel _gTextureWarioFace13_end

.align 2, 0x00
glabel _gTextureWarioFace14
.incbin "assets/character_select/wario/wario_face_14.mio0"
glabel _gTextureWarioFace14_end

.align 2, 0x00
glabel _gTextureWarioFace15
.incbin "assets/character_select/wario/wario_face_15.mio0"
glabel _gTextureWarioFace15_end

.align 2, 0x00
glabel _gTextureWarioFace16
.incbin "assets/character_select/wario/wario_face_16.mio0"
glabel _gTextureWarioFace16_end

.align 2, 0x00
glabel _gTextureBowserFace00
.incbin "assets/character_select/bowser/bowser_face_00.mio0"
glabel _gTextureBowserFace00_end

.align 2, 0x00
glabel _gTextureBowserFace01
.incbin "assets/character_select/bowser/bowser_face_01.mio0"
glabel _gTextureBowserFace01_end

.align 2, 0x00
glabel _gTextureBowserFace02
.incbin "assets/character_select/bowser/bowser_face_02.mio0"
glabel _gTextureBowserFace02_end

.align 2, 0x00
glabel _gTextureBowserFace03
.incbin "assets/character_select/bowser/bowser_face_03.mio0"
glabel _gTextureBowserFace03_end

.align 2, 0x00
glabel _gTextureBowserFace04
.incbin "assets/character_select/bowser/bowser_face_04.mio0"
glabel _gTextureBowserFace04_end

.align 2, 0x00
glabel _gTextureBowserFace05
.incbin "assets/character_select/bowser/bowser_face_05.mio0"
glabel _gTextureBowserFace05_end

.align 2, 0x00
glabel _gTextureBowserFace06
.incbin "assets/character_select/bowser/bowser_face_06.mio0"
glabel _gTextureBowserFace06_end

.align 2, 0x00
glabel _gTextureBowserFace07
.incbin "assets/character_select/bowser/bowser_face_07.mio0"
glabel _gTextureBowserFace07_end

.align 2, 0x00
glabel _gTextureBowserFace08
.incbin "assets/character_select/bowser/bowser_face_08.mio0"
glabel _gTextureBowserFace08_end

.align 2, 0x00
glabel _gTextureBowserFace09
.incbin "assets/character_select/bowser/bowser_face_09.mio0"
glabel _gTextureBowserFace09_end

.align 2, 0x00
glabel _gTextureBowserFace10
.incbin "assets/character_select/bowser/bowser_face_10.mio0"
glabel _gTextureBowserFace10_end

.align 2, 0x00
glabel _gTextureBowserFace11
.incbin "assets/character_select/bowser/bowser_face_11.mio0"
glabel _gTextureBowserFace11_end

.align 2, 0x00
glabel _gTextureBowserFace12
.incbin "assets/character_select/bowser/bowser_face_12.mio0"
glabel _gTextureBowserFace12_end

.align 2, 0x00
glabel _gTextureBowserFace13
.incbin "assets/character_select/bowser/bowser_face_13.mio0"
glabel _gTextureBowserFace13_end

.align 2, 0x00
glabel _gTextureBowserFace14
.incbin "assets/character_select/bowser/bowser_face_14.mio0"
glabel _gTextureBowserFace14_end

.align 2, 0x00
glabel _gTextureBowserFace15
.incbin "assets/character_select/bowser/bowser_face_15.mio0"
glabel _gTextureBowserFace15_end

.align 2, 0x00
glabel _gTextureBowserFace16
.incbin "assets/character_select/bowser/bowser_face_16.mio0"
glabel _gTextureBowserFace16_end

.align 2, 0x00
glabel _gTextureCoursePreviewMarioRaceway
.incbin "assets/course_previews/gTextureCoursePreviewMarioRaceway.mio0"

.align 2, 0x00
glabel _gTextureCoursePreviewChocoMountain
.incbin "assets/course_previews/gTextureCoursePreviewChocoMountain.mio0"

.align 2, 0x00
glabel _gTextureCoursePreviewBowsersCastle
.incbin "assets/course_previews/gTextureCoursePreviewBowsersCastle.mio0"

.align 2, 0x00
glabel _gTextureCoursePreviewBansheeBoardwalk
.incbin "assets/course_previews/gTextureCoursePreviewBansheeBoardwalk.mio0"

.align 2, 0x00
glabel _gTextureCoursePreviewYoshiValley
.incbin "assets/course_previews/gTextureCoursePreviewYoshiValley.mio0"

.align 2, 0x00
glabel _gTextureCoursePreviewFrappeSnowland
.incbin "assets/course_previews/gTextureCoursePreviewFrappeSnowland.mio0"

.align 2, 0x00
glabel _gTextureCoursePreviewKoopaTroopaBeach
.incbin "assets/course_previews/gTextureCoursePreviewKoopaTroopaBeach.mio0"

.align 2, 0x00
glabel _gTextureCoursePreviewRoyalRaceway
.incbin "assets/course_previews/gTextureCoursePreviewRoyalRaceway.mio0"

.align 2, 0x00
glabel _gTextureCoursePreviewLuigiRaceway
.incbin "assets/course_previews/gTextureCoursePreviewLuigiRaceway.mio0"

.align 2, 0x00
glabel _gTextureCoursePreviewMooMooFarm
.incbin "assets/course_previews/gTextureCoursePreviewMooMooFarm.mio0"

.align 2, 0x00
glabel _gTextureCoursePreviewToadsTurnpike
.incbin "assets/course_previews/gTextureCoursePreviewToadsTurnpike.mio0"

.align 2, 0x00
glabel _gTextureCoursePreviewKalimariDesert
.incbin "assets/course_previews/gTextureCoursePreviewKalimariDesert.mio0"

.align 2, 0x00
glabel _gTextureCoursePreviewSherbetLand
.incbin "assets/course_previews/gTextureCoursePreviewSherbetLand.mio0"

.align 2, 0x00
glabel _gTextureCoursePreviewRainbowRoad
.incbin "assets/course_previews/gTextureCoursePreviewRainbowRoad.mio0"

.align 2, 0x00
glabel _gTextureCoursePreviewWarioStadium
.incbin "assets/course_previews/gTextureCoursePreviewWarioStadium.mio0"

.align 2, 0x00
glabel _gTextureCoursePreviewBlockFort
.incbin "assets/course_previews/gTextureCoursePreviewBlockFort.mio0"

.align 2, 0x00
glabel _gTextureCoursePreviewSkyscraper
.incbin "assets/course_previews/gTextureCoursePreviewSkyscraper.mio0"

.align 2, 0x00
glabel _gTextureCoursePreviewDoubleDeck
.incbin "assets/course_previews/gTextureCoursePreviewDoubleDeck.mio0"

.align 2, 0x00
glabel _gTextureCoursePreviewDksJungleParkway
.incbin "assets/course_previews/gTextureCoursePreviewDksJungleParkway.mio0"

.align 2, 0x00
glabel _gTextureCoursePreviewBigDonut
.incbin "assets/course_previews/gTextureCoursePreviewBigDonut.mio0"

.align 2, 0x00
glabel _gTextureTrophyGold
.incbin "textures/standalone/trophy_gold.rgba16.mio0"
glabel _gTextureTrophyGold_end

.align 2, 0x00
glabel _gTextureTrophySilver
.incbin "textures/standalone/trophy_silver.rgba16.mio0"
glabel _gTextureTrophySilver_end

.align 2, 0x00
glabel _gTextureTrophyBronze
.incbin "textures/standalone/trophy_bronze.rgba16.mio0"
glabel _gTextureTrophyBronze_end

.align 2, 0x00
glabel _gTextureCupGold
.incbin "textures/standalone/cup_gold.rgba16.mio0"
glabel _gTextureCupGold_end

.align 2, 0x00
glabel _gTextureCupSilver
.incbin "textures/standalone/cup_silver.rgba16.mio0"
glabel _gTextureCupSilver_end

.align 2, 0x00
glabel _gTextureCupBronze
.incbin "textures/standalone/cup_bronze.rgba16.mio0"
glabel _gTextureCupBronze_end

.align 2, 0x00
glabel _gTexturePushStartButton
.incbin "textures/raw/push_start_button.rgba16"

.align 2, 0x00
glabel _gTextureCopyright1996
.incbin "textures/raw/copyright_1996.rgba16"

.align 2, 0x00
glabel _gTextureP1BorderBlue
.incbin "textures/raw/p1_border_blue.rgba16"

.align 2, 0x00
glabel _gTextureP2BorderRed
.incbin "textures/raw/p2_border_red.rgba16"

.align 2, 0x00
glabel _gTextureP3BorderOrange
.incbin "textures/raw/p3_border_orange.rgba16"

.align 2, 0x00
glabel _gTextureP4BorderGreen
.incbin "textures/raw/p4_border_green.rgba16"

.align 2, 0x00
glabel _gTextureSmallGreenTriangle
.incbin "textures/raw/small_green_triangle.rgba16"

.align 2, 0x00
glabel _gTexture7E56E4
.incbin "textures/standalone/texture_7E56E4.ia16.mio0"
glabel _gTexture7E56E4_end

