# Mario Kart 64 (U) disassembly and split file
# generated by n64split v0.4a - N64 ROM splitter

.include "macros.inc"

.data

.align 0x4,0x00
glabel __textures_0bSegmentStart
glabel __textures_0bSegmentRomStart

glabel _gTexturePlayerSelect
.incbin "bin/gTexturePlayerSelect.rgba16.tkmk00"
glabel _gTexturePlayerSelect_end

glabel _gTextureOption
.incbin "bin/gTextureOption.rgba16.tkmk00"
glabel _gTextureOption_end

glabel _gTextureNameDK
.incbin "bin/gTextureNameDK.rgba16.tkmk00"
glabel _gTextureNameDK_end

glabel _gTextureNameToad
.incbin "bin/gTextureNameToad.rgba16.tkmk00"
glabel _gTextureNameToad_end

glabel _gTextureNameBowser
.incbin "bin/gTextureNameBowser.rgba16.tkmk00"
glabel _gTextureNameBowser_end

glabel _gTextureNameLuigi
.incbin "bin/gTextureNameLuigi.rgba16.tkmk00"
glabel _gTextureNameLuigi_end

glabel _gTextureNameMario
.incbin "bin/gTextureNameMario.rgba16.tkmk00"
glabel _gTextureNameMario_end

glabel _gTextureNamePeach
.incbin "bin/gTextureNamePeach.rgba16.tkmk00"
glabel _gTextureNamePeach_end

glabel _gTextureNameWario
.incbin "bin/gTextureNameWario.rgba16.tkmk00"
glabel _gTextureNameWario_end

glabel _gTextureNameYoshi
.incbin "bin/gTextureNameYoshi.rgba16.tkmk00"
glabel _gTextureNameYoshi_end

glabel _gTextureTitleMarioRaceway
.incbin "bin/gTextureTitleMarioRaceway.rgba16.tkmk00"
glabel _gTextureTitleMarioRaceway_end

glabel _gTextureTitleChocoMountain
.incbin "bin/gTextureTitleChocoMountain.rgba16.tkmk00"
glabel _gTextureTitleChocoMountain_end

glabel _gTextureTitleBowsersCastle
.incbin "bin/gTextureTitleBowsersCastle.rgba16.tkmk00"
glabel _gTextureTitleBowsersCastle_end

glabel _gTextureTitleBansheeBoardwalk
.incbin "bin/gTextureTitleBansheeBoardwalk.rgba16.tkmk00"
glabel _gTextureTitleBansheeBoardwalk_end

glabel _gTextureTitleYoshiValley
.incbin "bin/gTextureTitleYoshiValley.rgba16.tkmk00"
glabel _gTextureTitleYoshiValley_end

glabel _gTextureTitleFrappeSnowland
.incbin "bin/gTextureTitleFrappeSnowland.rgba16.tkmk00"
glabel _gTextureTitleFrappeSnowland_end

glabel _gTextureTitleKoopaTroopaBeach
.incbin "bin/gTextureTitleKoopaTroopaBeach.rgba16.tkmk00"
glabel _gTextureTitleKoopaTroopaBeach_end

glabel _gTextureTitleRoyalRaceway
.incbin "bin/gTextureTitleRoyalRaceway.rgba16.tkmk00"
glabel _gTextureTitleRoyalRaceway_end

glabel _gTextureTitleLuigiRaceway
.incbin "bin/gTextureTitleLuigiRaceway.rgba16.tkmk00"
glabel _gTextureTitleLuigiRaceway_end

glabel _gTextureTitleMooMooFarm
.incbin "bin/gTextureTitleMooMooFarm.rgba16.tkmk00"
glabel _gTextureTitleMooMooFarm_end

glabel _gTextureTitleToadsTurnpike
.incbin "bin/gTextureTitleToadsTurnpike.rgba16.tkmk00"
glabel _gTextureTitleToadsTurnpike_end

glabel _gTextureTitleKalimariDesert
.incbin "bin/gTextureTitleKalimariDesert.rgba16.tkmk00"
glabel _gTextureTitleKalimariDesert_end

glabel _gTextureTitleSherbetLand
.incbin "bin/gTextureTitleSherbetLand.rgba16.tkmk00"
glabel _gTextureTitleSherbetLand_end

glabel _gTextureTitleRainbowRoad
.incbin "bin/gTextureTitleRainbowRoad.rgba16.tkmk00"
glabel _gTextureTitleRainbowRoad_end

glabel _gTextureTitleWarioStadium
.incbin "bin/gTextureTitleWarioStadium.rgba16.tkmk00"
glabel _gTextureTitleWarioStadium_end

glabel _gTextureTitleBlockFort
.incbin "bin/gTextureTitleBlockFort.rgba16.tkmk00"
glabel _gTextureTitleBlockFort_end

glabel _gTextureTitleSkyscraper
.incbin "bin/gTextureTitleSkyscraper.rgba16.tkmk00"
glabel _gTextureTitleSkyscraper_end

glabel _gTextureTitleDoubleDeck
.incbin "bin/gTextureTitleDoubleDeck.rgba16.tkmk00"
glabel _gTextureTitleDoubleDeck_end

glabel _gTextureTitleDKsJungleParkway
.incbin "bin/gTextureTitleDKsJungleParkway.rgba16.tkmk00"
glabel _gTextureTitleDKsJungleParkway_end

glabel _gTextureTitleBigDonut
.incbin "bin/gTextureTitleBigDonut.rgba16.tkmk00"
glabel _gTextureTitleBigDonut_end

glabel _gTextureMapSelect
.incbin "bin/gTextureMapSelect.rgba16.tkmk00"
glabel _gTextureMapSelect_end

glabel _gTextureMenuFlowerCup
.incbin "bin/gTextureMenuFlowerCup.rgba16.tkmk00"
glabel _gTextureMenuFlowerCup_end

glabel _gTextureMenuMushroomCup
.incbin "bin/gTextureMenuMushroomCup.rgba16.tkmk00"
glabel _gTextureMenuMushroomCup_end

glabel _gTextureMenuStarCup
.incbin "bin/gTextureMenuStarCup.rgba16.tkmk00"
glabel _gTextureMenuStarCup_end

glabel _gTextureMenuSpecialCup
.incbin "bin/gTextureMenuSpecialCup.rgba16.tkmk00"
glabel _gTextureMenuSpecialCup_end

glabel _gTextureGameSelect
.incbin "bin/gTextureGameSelect.rgba16.tkmk00"
glabel _gTextureGameSelect_end

glabel _gTextureMenu1PGame
.incbin "bin/gTextureMenu1PGame.rgba16.tkmk00"
glabel _gTextureMenu1PGame_end

glabel _gTextureMenu2PGame
.incbin "bin/gTextureMenu2PGame.rgba16.tkmk00"
glabel _gTextureMenu2PGame_end

glabel _gTextureMenu3PGame
.incbin "bin/gTextureMenu3PGame.rgba16.tkmk00"
glabel _gTextureMenu3PGame_end

glabel _gTextureMenu4PGame
.incbin "bin/gTextureMenu4PGame.rgba16.tkmk00"
glabel _gTextureMenu4PGame_end

glabel _gTextureMenuModeBattle
.incbin "bin/gTextureMenuModeBattle.rgba16.tkmk00"
glabel _gTextureMenuModeBattle_end

glabel _gTextureMenuModeTimeTrials
.incbin "bin/gTextureMenuModeTimeTrials.rgba16.tkmk00"
glabel _gTextureMenuModeTimeTrials_end

glabel _gTextureMenuModeMarioGP
.incbin "bin/gTextureMenuModeMarioGP.rgba16.tkmk00"
glabel _gTextureMenuModeMarioGP_end

glabel _gTextureMenuModeVS
.incbin "bin/gTextureMenuModeVS.rgba16.tkmk00"
glabel _gTextureMenuModeVS_end

glabel _gTextureMenuLOption
.incbin "bin/gTextureMenuLOption.rgba16.tkmk00"
glabel _gTextureMenuLOption_end

glabel _gTextureMenuRData
.incbin "bin/gTextureMenuRData.rgba16.tkmk00"
glabel _gTextureMenuRData_end

glabel _gTextureMenu50cc
.incbin "bin/gTextureMenu50cc.rgba16.tkmk00"
glabel _gTextureMenu50cc_end

glabel _gTextureMenu100cc
.incbin "bin/gTextureMenu100cc.rgba16.tkmk00"
glabel _gTextureMenu100cc_end

glabel _gTextureMenu150cc
.incbin "bin/gTextureMenu150cc.rgba16.tkmk00"
glabel _gTextureMenu150cc_end

glabel _gTextureMenuExtra
.incbin "bin/gTextureMenuExtra.rgba16.tkmk00"
glabel _gTextureMenuExtra_end

glabel _gTextureMenuWithoutItem
.incbin "bin/gTextureMenuWithoutItem.rgba16.tkmk00"
glabel _gTextureMenuWithoutItem_end

glabel _gTextureMenuWithItem
.incbin "bin/gTextureMenuWithItem.rgba16.tkmk00"
glabel _gTextureMenuWithItem_end

glabel _gTextureMenuBegin
.incbin "bin/gTextureMenuBegin.rgba16.tkmk00"
glabel _gTextureMenuBegin_end

glabel _gTextureMenuGhost
.incbin "bin/gTextureMenuGhost.rgba16.tkmk00"
glabel _gTextureMenuGhost_end

glabel _gTextureMenuData
.incbin "bin/gTextureMenuData.rgba16.tkmk00"
glabel _gTextureMenuData_end

glabel _gTextureMenuOK
.incbin "bin/gTextureMenuOK.rgba16.tkmk00"
glabel _gTextureMenuOK_end

glabel _gTextureBackgroundBlueSky
.incbin "bin/gTextureBackgroundBlueSky.rgba16.tkmk00"
glabel _gTextureBackgroundBlueSky_end

glabel _gTextureBackgroundSunset
.incbin "bin/gTextureBackgroundSunset.rgba16.tkmk00"
glabel _gTextureBackgroundSunset_end

glabel _gTextureGreenGoldStripe
.incbin "bin/gTextureGreenGoldStripe.rgba16.tkmk00"
glabel _gTextureGreenGoldStripe_end

glabel _gTextureGoldStripe
.incbin "bin/gTextureGoldStripe.rgba16.tkmk00"
glabel _gTextureGoldStripe_end

glabel _gTextureWhiteStripe
.incbin "bin/gTextureWhiteStripe.rgba16.tkmk00"
glabel _gTextureWhiteStripe_end

glabel _gTexturePinkBar
.incbin "bin/gTexturePinkBar.rgba16.tkmk00"
glabel _gTexturePinkBar_end

glabel _gTextureGoldBar
.incbin "bin/gTextureGoldBar.rgba16.tkmk00"
glabel _gTextureGoldBar_end

.align 0x10, 0x00

glabel __textures_0bSegmentEnd
glabel __textures_0bSegmentRomEnd
glabel __textures_0bSegmentSize
.long (__textures_0bSegmentEnd - __textures_0bSegmentStart)
