# Mario Kart 64 (U) disassembly and split file
# generated by n64split v0.4a - N64 ROM splitter

.include "macros.inc"

.data

# segment 0x0A000000 (0x729A30 - 0x7E684F)

.align 2, 0x00
glabel __textures_0aSegmentStart
glabel __textures_0aSegmentRomStart
glabel _gTextureMarioFace00
.incbin "assets/character_select/mario/mario_face_00.mio0"
glabel _gTextureMarioFace00_end

.align 2, 0x00
glabel _gTextureMarioFace01
.incbin "assets/character_select/mario/mario_face_01.mio0"
glabel _gTextureMarioFace01_end

.align 2, 0x00
glabel _gTextureMarioFace02
.incbin "assets/character_select/mario/mario_face_02.mio0"
glabel _gTextureMarioFace02_end

.align 2, 0x00
glabel _gTextureMarioFace03
.incbin "assets/character_select/mario/mario_face_03.mio0"
glabel _gTextureMarioFace03_end

.align 2, 0x00
glabel _gTextureMarioFace04
.incbin "assets/character_select/mario/mario_face_04.mio0"
glabel _gTextureMarioFace04_end

.align 2, 0x00
glabel _gTextureMarioFace05
.incbin "assets/character_select/mario/mario_face_05.mio0"
glabel _gTextureMarioFace05_end

.align 2, 0x00
glabel _gTextureMarioFace06
.incbin "assets/character_select/mario/mario_face_06.mio0"
glabel _gTextureMarioFace06_end

.align 2, 0x00
glabel _gTextureMarioFace07
.incbin "assets/character_select/mario/mario_face_07.mio0"
glabel _gTextureMarioFace07_end

.align 2, 0x00
glabel _gTextureMarioFace08
.incbin "assets/character_select/mario/mario_face_08.mio0"
glabel _gTextureMarioFace08_end

.align 2, 0x00
glabel _gTextureMarioFace09
.incbin "assets/character_select/mario/mario_face_09.mio0"
glabel _gTextureMarioFace09_end

.align 2, 0x00
glabel _gTextureMarioFace10
.incbin "assets/character_select/mario/mario_face_10.mio0"
glabel _gTextureMarioFace10_end

.align 2, 0x00
glabel _gTextureMarioFace11
.incbin "assets/character_select/mario/mario_face_11.mio0"
glabel _gTextureMarioFace11_end

.align 2, 0x00
glabel _gTextureMarioFace12
.incbin "assets/character_select/mario/mario_face_12.mio0"
glabel _gTextureMarioFace12_end

.align 2, 0x00
glabel _gTextureMarioFace13
.incbin "assets/character_select/mario/mario_face_13.mio0"
glabel _gTextureMarioFace13_end

.align 2, 0x00
glabel _gTextureMarioFace14
.incbin "assets/character_select/mario/mario_face_14.mio0"
glabel _gTextureMarioFace14_end

.align 2, 0x00
glabel _gTextureMarioFace15
.incbin "assets/character_select/mario/mario_face_15.mio0"
glabel _gTextureMarioFace15_end

.align 2, 0x00
glabel _gTextureMarioFace16
.incbin "assets/character_select/mario/mario_face_16.mio0"
glabel _gTextureMarioFace16_end

.align 2, 0x00
glabel _gTextureLuigiFace00
.incbin "assets/character_select/luigi/luigi_face_00.mio0"
glabel _gTextureLuigiFace00_end

.align 2, 0x00
glabel _gTextureLuigiFace01
.incbin "assets/character_select/luigi/luigi_face_01.mio0"
glabel _gTextureLuigiFace01_end

.align 2, 0x00
glabel _gTextureLuigiFace02
.incbin "assets/character_select/luigi/luigi_face_02.mio0"
glabel _gTextureLuigiFace02_end

.align 2, 0x00
glabel _gTextureLuigiFace03
.incbin "assets/character_select/luigi/luigi_face_03.mio0"
glabel _gTextureLuigiFace03_end

.align 2, 0x00
glabel _gTextureLuigiFace04
.incbin "assets/character_select/luigi/luigi_face_04.mio0"
glabel _gTextureLuigiFace04_end

.align 2, 0x00
glabel _gTextureLuigiFace05
.incbin "assets/character_select/luigi/luigi_face_05.mio0"
glabel _gTextureLuigiFace05_end

.align 2, 0x00
glabel _gTextureLuigiFace06
.incbin "assets/character_select/luigi/luigi_face_06.mio0"
glabel _gTextureLuigiFace06_end

.align 2, 0x00
glabel _gTextureLuigiFace07
.incbin "assets/character_select/luigi/luigi_face_07.mio0"
glabel _gTextureLuigiFace07_end

.align 2, 0x00
glabel _gTextureLuigiFace08
.incbin "assets/character_select/luigi/luigi_face_08.mio0"
glabel _gTextureLuigiFace08_end

.align 2, 0x00
glabel _gTextureLuigiFace09
.incbin "assets/character_select/luigi/luigi_face_09.mio0"
glabel _gTextureLuigiFace09_end

.align 2, 0x00
glabel _gTextureLuigiFace10
.incbin "assets/character_select/luigi/luigi_face_10.mio0"
glabel _gTextureLuigiFace10_end

.align 2, 0x00
glabel _gTextureLuigiFace11
.incbin "assets/character_select/luigi/luigi_face_11.mio0"
glabel _gTextureLuigiFace11_end

.align 2, 0x00
glabel _gTextureLuigiFace12
.incbin "assets/character_select/luigi/luigi_face_12.mio0"
glabel _gTextureLuigiFace12_end

.align 2, 0x00
glabel _gTextureLuigiFace13
.incbin "assets/character_select/luigi/luigi_face_13.mio0"
glabel _gTextureLuigiFace13_end

.align 2, 0x00
glabel _gTextureLuigiFace14
.incbin "assets/character_select/luigi/luigi_face_14.mio0"
glabel _gTextureLuigiFace14_end

.align 2, 0x00
glabel _gTextureLuigiFace15
.incbin "assets/character_select/luigi/luigi_face_15.mio0"
glabel _gTextureLuigiFace15_end

.align 2, 0x00
glabel _gTextureLuigiFace16
.incbin "assets/character_select/luigi/luigi_face_16.mio0"
glabel _gTextureLuigiFace16_end

.align 2, 0x00
glabel _gTexturePeachFace00
.incbin "assets/character_select/peach/peach_face_00.mio0"
glabel _gTexturePeachFace00_end

.align 2, 0x00
glabel _gTexturePeachFace01
.incbin "assets/character_select/peach/peach_face_01.mio0"
glabel _gTexturePeachFace01_end

.align 2, 0x00
glabel _gTexturePeachFace02
.incbin "assets/character_select/peach/peach_face_02.mio0"
glabel _gTexturePeachFace02_end

.align 2, 0x00
glabel _gTexturePeachFace03
.incbin "assets/character_select/peach/peach_face_03.mio0"
glabel _gTexturePeachFace03_end

.align 2, 0x00
glabel _gTexturePeachFace04
.incbin "assets/character_select/peach/peach_face_04.mio0"
glabel _gTexturePeachFace04_end

.align 2, 0x00
glabel _gTexturePeachFace05
.incbin "assets/character_select/peach/peach_face_05.mio0"
glabel _gTexturePeachFace05_end

.align 2, 0x00
glabel _gTexturePeachFace06
.incbin "assets/character_select/peach/peach_face_06.mio0"
glabel _gTexturePeachFace06_end

.align 2, 0x00
glabel _gTexturePeachFace07
.incbin "assets/character_select/peach/peach_face_07.mio0"
glabel _gTexturePeachFace07_end

.align 2, 0x00
glabel _gTexturePeachFace08
.incbin "assets/character_select/peach/peach_face_08.mio0"
glabel _gTexturePeachFace08_end

.align 2, 0x00
glabel _gTexturePeachFace09
.incbin "assets/character_select/peach/peach_face_09.mio0"
glabel _gTexturePeachFace09_end

.align 2, 0x00
glabel _gTexturePeachFace10
.incbin "assets/character_select/peach/peach_face_10.mio0"
glabel _gTexturePeachFace10_end

.align 2, 0x00
glabel _gTexturePeachFace11
.incbin "assets/character_select/peach/peach_face_11.mio0"
glabel _gTexturePeachFace11_end

.align 2, 0x00
glabel _gTexturePeachFace12
.incbin "assets/character_select/peach/peach_face_12.mio0"
glabel _gTexturePeachFace12_end

.align 2, 0x00
glabel _gTexturePeachFace13
.incbin "assets/character_select/peach/peach_face_13.mio0"
glabel _gTexturePeachFace13_end

.align 2, 0x00
glabel _gTexturePeachFace14
.incbin "assets/character_select/peach/peach_face_14.mio0"
glabel _gTexturePeachFace14_end

.align 2, 0x00
glabel _gTexturePeachFace15
.incbin "assets/character_select/peach/peach_face_15.mio0"
glabel _gTexturePeachFace15_end

.align 2, 0x00
glabel _gTexturePeachFace16
.incbin "assets/character_select/peach/peach_face_16.mio0"
glabel _gTexturePeachFace16_end

.align 2, 0x00
glabel _gTextureToadFace00
.incbin "assets/character_select/toad/toad_face_00.mio0"
glabel _gTextureToadFace00_end

.align 2, 0x00
glabel _gTextureToadFace01
.incbin "assets/character_select/toad/toad_face_01.mio0"
glabel _gTextureToadFace01_end

.align 2, 0x00
glabel _gTextureToadFace02
.incbin "assets/character_select/toad/toad_face_02.mio0"
glabel _gTextureToadFace02_end

.align 2, 0x00
glabel _gTextureToadFace03
.incbin "assets/character_select/toad/toad_face_03.mio0"
glabel _gTextureToadFace03_end

.align 2, 0x00
glabel _gTextureToadFace04
.incbin "assets/character_select/toad/toad_face_04.mio0"
glabel _gTextureToadFace04_end

.align 2, 0x00
glabel _gTextureToadFace05
.incbin "assets/character_select/toad/toad_face_05.mio0"
glabel _gTextureToadFace05_end

.align 2, 0x00
glabel _gTextureToadFace06
.incbin "assets/character_select/toad/toad_face_06.mio0"
glabel _gTextureToadFace06_end

.align 2, 0x00
glabel _gTextureToadFace07
.incbin "assets/character_select/toad/toad_face_07.mio0"
glabel _gTextureToadFace07_end

.align 2, 0x00
glabel _gTextureToadFace08
.incbin "assets/character_select/toad/toad_face_08.mio0"
glabel _gTextureToadFace08_end

.align 2, 0x00
glabel _gTextureToadFace09
.incbin "assets/character_select/toad/toad_face_09.mio0"
glabel _gTextureToadFace09_end

.align 2, 0x00
glabel _gTextureToadFace10
.incbin "assets/character_select/toad/toad_face_10.mio0"
glabel _gTextureToadFace10_end

.align 2, 0x00
glabel _gTextureToadFace11
.incbin "assets/character_select/toad/toad_face_11.mio0"
glabel _gTextureToadFace11_end

.align 2, 0x00
glabel _gTextureToadFace12
.incbin "assets/character_select/toad/toad_face_12.mio0"
glabel _gTextureToadFace12_end

.align 2, 0x00
glabel _gTextureToadFace13
.incbin "assets/character_select/toad/toad_face_13.mio0"
glabel _gTextureToadFace13_end

.align 2, 0x00
glabel _gTextureToadFace14
.incbin "assets/character_select/toad/toad_face_14.mio0"
glabel _gTextureToadFace14_end

.align 2, 0x00
glabel _gTextureToadFace15
.incbin "assets/character_select/toad/toad_face_15.mio0"
glabel _gTextureToadFace15_end

.align 2, 0x00
glabel _gTextureToadFace16
.incbin "assets/character_select/toad/toad_face_16.mio0"
glabel _gTextureToadFace16_end

.align 2, 0x00
glabel _gTextureYoshiFace00
.incbin "assets/character_select/yoshi/yoshi_face_00.mio0"
glabel _gTextureYoshiFace00_end

.align 2, 0x00
glabel _gTextureYoshiFace01
.incbin "assets/character_select/yoshi/yoshi_face_01.mio0"
glabel _gTextureYoshiFace01_end

.align 2, 0x00
glabel _gTextureYoshiFace02
.incbin "assets/character_select/yoshi/yoshi_face_02.mio0"
glabel _gTextureYoshiFace02_end

.align 2, 0x00
glabel _gTextureYoshiFace03
.incbin "assets/character_select/yoshi/yoshi_face_03.mio0"
glabel _gTextureYoshiFace03_end

.align 2, 0x00
glabel _gTextureYoshiFace04
.incbin "assets/character_select/yoshi/yoshi_face_04.mio0"
glabel _gTextureYoshiFace04_end

.align 2, 0x00
glabel _gTextureYoshiFace05
.incbin "assets/character_select/yoshi/yoshi_face_05.mio0"
glabel _gTextureYoshiFace05_end

.align 2, 0x00
glabel _gTextureYoshiFace06
.incbin "assets/character_select/yoshi/yoshi_face_06.mio0"
glabel _gTextureYoshiFace06_end

.align 2, 0x00
glabel _gTextureYoshiFace07
.incbin "assets/character_select/yoshi/yoshi_face_07.mio0"
glabel _gTextureYoshiFace07_end

.align 2, 0x00
glabel _gTextureYoshiFace08
.incbin "assets/character_select/yoshi/yoshi_face_08.mio0"
glabel _gTextureYoshiFace08_end

.align 2, 0x00
glabel _gTextureYoshiFace09
.incbin "assets/character_select/yoshi/yoshi_face_09.mio0"
glabel _gTextureYoshiFace09_end

.align 2, 0x00
glabel _gTextureYoshiFace10
.incbin "assets/character_select/yoshi/yoshi_face_10.mio0"
glabel _gTextureYoshiFace10_end

.align 2, 0x00
glabel _gTextureYoshiFace11
.incbin "assets/character_select/yoshi/yoshi_face_11.mio0"
glabel _gTextureYoshiFace11_end

.align 2, 0x00
glabel _gTextureYoshiFace12
.incbin "assets/character_select/yoshi/yoshi_face_12.mio0"
glabel _gTextureYoshiFace12_end

.align 2, 0x00
glabel _gTextureYoshiFace13
.incbin "assets/character_select/yoshi/yoshi_face_13.mio0"
glabel _gTextureYoshiFace13_end

.align 2, 0x00
glabel _gTextureYoshiFace14
.incbin "assets/character_select/yoshi/yoshi_face_14.mio0"
glabel _gTextureYoshiFace14_end

.align 2, 0x00
glabel _gTextureYoshiFace15
.incbin "assets/character_select/yoshi/yoshi_face_15.mio0"
glabel _gTextureYoshiFace15_end

.align 2, 0x00
glabel _gTextureYoshiFace16
.incbin "assets/character_select/yoshi/yoshi_face_16.mio0"
glabel _gTextureYoshiFace16_end

.align 2, 0x00
glabel _gTextureDkFace00
.incbin "assets/character_select/donkeykong/donkeykong_face_00.mio0"
glabel _gTextureDkFace00_end

.align 2, 0x00
glabel _gTextureDkFace01
.incbin "assets/character_select/donkeykong/donkeykong_face_01.mio0"
glabel _gTextureDkFace01_end

.align 2, 0x00
glabel _gTextureDkFace02
.incbin "assets/character_select/donkeykong/donkeykong_face_02.mio0"
glabel _gTextureDkFace02_end

.align 2, 0x00
glabel _gTextureDkFace03
.incbin "assets/character_select/donkeykong/donkeykong_face_03.mio0"
glabel _gTextureDkFace03_end

.align 2, 0x00
glabel _gTextureDkFace04
.incbin "assets/character_select/donkeykong/donkeykong_face_04.mio0"
glabel _gTextureDkFace04_end

.align 2, 0x00
glabel _gTextureDkFace05
.incbin "assets/character_select/donkeykong/donkeykong_face_05.mio0"
glabel _gTextureDkFace05_end

.align 2, 0x00
glabel _gTextureDkFace06
.incbin "assets/character_select/donkeykong/donkeykong_face_06.mio0"
glabel _gTextureDkFace06_end

.align 2, 0x00
glabel _gTextureDkFace07
.incbin "assets/character_select/donkeykong/donkeykong_face_07.mio0"
glabel _gTextureDkFace07_end

.align 2, 0x00
glabel _gTextureDkFace08
.incbin "assets/character_select/donkeykong/donkeykong_face_08.mio0"
glabel _gTextureDkFace08_end

.align 2, 0x00
glabel _gTextureDkFace09
.incbin "assets/character_select/donkeykong/donkeykong_face_09.mio0"
glabel _gTextureDkFace09_end

.align 2, 0x00
glabel _gTextureDkFace10
.incbin "assets/character_select/donkeykong/donkeykong_face_10.mio0"
glabel _gTextureDkFace10_end

.align 2, 0x00
glabel _gTextureDkFace11
.incbin "assets/character_select/donkeykong/donkeykong_face_11.mio0"
glabel _gTextureDkFace11_end

.align 2, 0x00
glabel _gTextureDkFace12
.incbin "assets/character_select/donkeykong/donkeykong_face_12.mio0"
glabel _gTextureDkFace12_end

.align 2, 0x00
glabel _gTextureDkFace13
.incbin "assets/character_select/donkeykong/donkeykong_face_13.mio0"
glabel _gTextureDkFace13_end

.align 2, 0x00
glabel _gTextureDkFace14
.incbin "assets/character_select/donkeykong/donkeykong_face_14.mio0"
glabel _gTextureDkFace14_end

.align 2, 0x00
glabel _gTextureDkFace15
.incbin "assets/character_select/donkeykong/donkeykong_face_15.mio0"
glabel _gTextureDkFace15_end

.align 2, 0x00
glabel _gTextureDkFace16
.incbin "assets/character_select/donkeykong/donkeykong_face_16.mio0"
glabel _gTextureDkFace16_end

.align 2, 0x00
glabel _gTextureWarioFace00
.incbin "assets/character_select/wario/wario_face_00.mio0"
glabel _gTextureWarioFace00_end

.align 2, 0x00
glabel _gTextureWarioFace01
.incbin "assets/character_select/wario/wario_face_01.mio0"
glabel _gTextureWarioFace01_end

.align 2, 0x00
glabel _gTextureWarioFace02
.incbin "assets/character_select/wario/wario_face_02.mio0"
glabel _gTextureWarioFace02_end

.align 2, 0x00
glabel _gTextureWarioFace03
.incbin "assets/character_select/wario/wario_face_03.mio0"
glabel _gTextureWarioFace03_end

.align 2, 0x00
glabel _gTextureWarioFace04
.incbin "assets/character_select/wario/wario_face_04.mio0"
glabel _gTextureWarioFace04_end

.align 2, 0x00
glabel _gTextureWarioFace05
.incbin "assets/character_select/wario/wario_face_05.mio0"
glabel _gTextureWarioFace05_end

.align 2, 0x00
glabel _gTextureWarioFace06
.incbin "assets/character_select/wario/wario_face_06.mio0"
glabel _gTextureWarioFace06_end

.align 2, 0x00
glabel _gTextureWarioFace07
.incbin "assets/character_select/wario/wario_face_07.mio0"
glabel _gTextureWarioFace07_end

.align 2, 0x00
glabel _gTextureWarioFace08
.incbin "assets/character_select/wario/wario_face_08.mio0"
glabel _gTextureWarioFace08_end

.align 2, 0x00
glabel _gTextureWarioFace09
.incbin "assets/character_select/wario/wario_face_09.mio0"
glabel _gTextureWarioFace09_end

.align 2, 0x00
glabel _gTextureWarioFace10
.incbin "assets/character_select/wario/wario_face_10.mio0"
glabel _gTextureWarioFace10_end

.align 2, 0x00
glabel _gTextureWarioFace11
.incbin "assets/character_select/wario/wario_face_11.mio0"
glabel _gTextureWarioFace11_end

.align 2, 0x00
glabel _gTextureWarioFace12
.incbin "assets/character_select/wario/wario_face_12.mio0"
glabel _gTextureWarioFace12_end

.align 2, 0x00
glabel _gTextureWarioFace13
.incbin "assets/character_select/wario/wario_face_13.mio0"
glabel _gTextureWarioFace13_end

.align 2, 0x00
glabel _gTextureWarioFace14
.incbin "assets/character_select/wario/wario_face_14.mio0"
glabel _gTextureWarioFace14_end

.align 2, 0x00
glabel _gTextureWarioFace15
.incbin "assets/character_select/wario/wario_face_15.mio0"
glabel _gTextureWarioFace15_end

.align 2, 0x00
glabel _gTextureWarioFace16
.incbin "assets/character_select/wario/wario_face_16.mio0"
glabel _gTextureWarioFace16_end

.align 2, 0x00
glabel _gTextureBowserFace00
.incbin "assets/character_select/bowser/bowser_face_00.mio0"
glabel _gTextureBowserFace00_end

.align 2, 0x00
glabel _gTextureBowserFace01
.incbin "assets/character_select/bowser/bowser_face_01.mio0"
glabel _gTextureBowserFace01_end

.align 2, 0x00
glabel _gTextureBowserFace02
.incbin "assets/character_select/bowser/bowser_face_02.mio0"
glabel _gTextureBowserFace02_end

.align 2, 0x00
glabel _gTextureBowserFace03
.incbin "assets/character_select/bowser/bowser_face_03.mio0"
glabel _gTextureBowserFace03_end

.align 2, 0x00
glabel _gTextureBowserFace04
.incbin "assets/character_select/bowser/bowser_face_04.mio0"
glabel _gTextureBowserFace04_end

.align 2, 0x00
glabel _gTextureBowserFace05
.incbin "assets/character_select/bowser/bowser_face_05.mio0"
glabel _gTextureBowserFace05_end

.align 2, 0x00
glabel _gTextureBowserFace06
.incbin "assets/character_select/bowser/bowser_face_06.mio0"
glabel _gTextureBowserFace06_end

.align 2, 0x00
glabel _gTextureBowserFace07
.incbin "assets/character_select/bowser/bowser_face_07.mio0"
glabel _gTextureBowserFace07_end

.align 2, 0x00
glabel _gTextureBowserFace08
.incbin "assets/character_select/bowser/bowser_face_08.mio0"
glabel _gTextureBowserFace08_end

.align 2, 0x00
glabel _gTextureBowserFace09
.incbin "assets/character_select/bowser/bowser_face_09.mio0"
glabel _gTextureBowserFace09_end

.align 2, 0x00
glabel _gTextureBowserFace10
.incbin "assets/character_select/bowser/bowser_face_10.mio0"
glabel _gTextureBowserFace10_end

.align 2, 0x00
glabel _gTextureBowserFace11
.incbin "assets/character_select/bowser/bowser_face_11.mio0"
glabel _gTextureBowserFace11_end

.align 2, 0x00
glabel _gTextureBowserFace12
.incbin "assets/character_select/bowser/bowser_face_12.mio0"
glabel _gTextureBowserFace12_end

.align 2, 0x00
glabel _gTextureBowserFace13
.incbin "assets/character_select/bowser/bowser_face_13.mio0"
glabel _gTextureBowserFace13_end

.align 2, 0x00
glabel _gTextureBowserFace14
.incbin "assets/character_select/bowser/bowser_face_14.mio0"
glabel _gTextureBowserFace14_end

.align 2, 0x00
glabel _gTextureBowserFace15
.incbin "assets/character_select/bowser/bowser_face_15.mio0"
glabel _gTextureBowserFace15_end

.align 2, 0x00
glabel _gTextureBowserFace16
.incbin "assets/character_select/bowser/bowser_face_16.mio0"
glabel _gTextureBowserFace16_end

.align 2, 0x00
glabel _gTextureCoursePreviewMarioRaceway
.incbin "assets/course_previews/gTextureCoursePreviewMarioRaceway.mio0"

.align 2, 0x00
glabel _gTextureCoursePreviewChocoMountain
.incbin "assets/course_previews/gTextureCoursePreviewChocoMountain.mio0"

.align 2, 0x00
glabel _gTextureCoursePreviewBowsersCastle
.incbin "assets/course_previews/gTextureCoursePreviewBowsersCastle.mio0"

.align 2, 0x00
glabel _gTextureCoursePreviewBansheeBoardwalk
.incbin "assets/course_previews/gTextureCoursePreviewBansheeBoardwalk.mio0"

.align 2, 0x00
glabel _gTextureCoursePreviewYoshiValley
.incbin "assets/course_previews/gTextureCoursePreviewYoshiValley.mio0"

.align 2, 0x00
glabel _gTextureCoursePreviewFrappeSnowland
.incbin "assets/course_previews/gTextureCoursePreviewFrappeSnowland.mio0"

.align 2, 0x00
glabel _gTextureCoursePreviewKoopaTroopaBeach
.incbin "assets/course_previews/gTextureCoursePreviewKoopaTroopaBeach.mio0"

.align 2, 0x00
glabel _gTextureCoursePreviewRoyalRaceway
.incbin "assets/course_previews/gTextureCoursePreviewRoyalRaceway.mio0"

.align 2, 0x00
glabel _gTextureCoursePreviewLuigiRaceway
.incbin "assets/course_previews/gTextureCoursePreviewLuigiRaceway.mio0"

.align 2, 0x00
glabel _gTextureCoursePreviewMooMooFarm
.incbin "assets/course_previews/gTextureCoursePreviewMooMooFarm.mio0"

.align 2, 0x00
glabel _gTextureCoursePreviewToadsTurnpike
.incbin "assets/course_previews/gTextureCoursePreviewToadsTurnpike.mio0"

.align 2, 0x00
glabel _gTextureCoursePreviewKalimariDesert
.incbin "assets/course_previews/gTextureCoursePreviewKalimariDesert.mio0"

.align 2, 0x00
glabel _gTextureCoursePreviewSherbetLand
.incbin "assets/course_previews/gTextureCoursePreviewSherbetLand.mio0"

.align 2, 0x00
glabel _gTextureCoursePreviewRainbowRoad
.incbin "assets/course_previews/gTextureCoursePreviewRainbowRoad.mio0"

.align 2, 0x00
glabel _gTextureCoursePreviewWarioStadium
.incbin "assets/course_previews/gTextureCoursePreviewWarioStadium.mio0"

.align 2, 0x00
glabel _gTextureCoursePreviewBlockFort
.incbin "assets/course_previews/gTextureCoursePreviewBlockFort.mio0"

.align 2, 0x00
glabel _gTextureCoursePreviewSkyscraper
.incbin "assets/course_previews/gTextureCoursePreviewSkyscraper.mio0"

.align 2, 0x00
glabel _gTextureCoursePreviewDoubleDeck
.incbin "assets/course_previews/gTextureCoursePreviewDoubleDeck.mio0"

.align 2, 0x00
glabel _gTextureCoursePreviewDksJungleParkway
.incbin "assets/course_previews/gTextureCoursePreviewDksJungleParkway.mio0"

.align 2, 0x00
glabel _gTextureCoursePreviewBigDonut
.incbin "assets/course_previews/gTextureCoursePreviewBigDonut.mio0"

.align 2, 0x00
glabel _gTextureTrophyGold
.incbin "textures/standalone/trophy_gold.rgba16.mio0"
glabel _gTextureTrophyGold_end

.align 2, 0x00
glabel _gTextureTrophySilver
.incbin "textures/standalone/trophy_silver.rgba16.mio0"
glabel _gTextureTrophySilver_end

.align 2, 0x00
glabel _gTextureTrophyBronze
.incbin "textures/standalone/trophy_bronze.rgba16.mio0"
glabel _gTextureTrophyBronze_end

.align 2, 0x00
glabel _gTextureCupGold
.incbin "textures/standalone/cup_gold.rgba16.mio0"
glabel _gTextureCupGold_end

.align 2, 0x00
glabel _gTextureCupSilver
.incbin "textures/standalone/cup_silver.rgba16.mio0"
glabel _gTextureCupSilver_end

.align 2, 0x00
glabel _gTextureCupBronze
.incbin "textures/standalone/cup_bronze.rgba16.mio0"
glabel _gTextureCupBronze_end

.align 2, 0x00
glabel _gTexturePushStartButton
.incbin "textures/raw/push_start_button.rgba16"

.align 2, 0x00
glabel _gTextureCopyright1996
.incbin "textures/raw/copyright_1996.rgba16"

.align 2, 0x00
glabel _gTextureP1BorderBlue
.incbin "textures/raw/p1_border_blue.rgba16"

.align 2, 0x00
glabel _gTextureP2BorderRed
.incbin "textures/raw/p2_border_red.rgba16"

.align 2, 0x00
glabel _gTextureP3BorderOrange
.incbin "textures/raw/p3_border_orange.rgba16"

.align 2, 0x00
glabel _gTextureP4BorderGreen
.incbin "textures/raw/p4_border_green.rgba16"

.align 2, 0x00
glabel _gTextureSmallGreenTriangle
.incbin "textures/raw/small_green_triangle.rgba16"

.align 2, 0x00
glabel _gTexture7E56E4
.incbin "textures/standalone/texture_7E56E4.ia16.mio0"
glabel _gTexture7E56E4_end

# Mario Kart 64 (U) disassembly and split file
# generated by n64split v0.4a - N64 ROM splitter



.data

# (0x7E6850 - ?)

.align 2, 0x00
glabel _gTextureSmallFont0
.incbin "textures/standalone/small_letter_0.ia16.mio0"
glabel _gTextureSmallFont0_end

.align 2, 0x00
glabel _gTextureSmallFont1
.incbin "textures/standalone/small_letter_1.ia16.mio0"
glabel _gTextureSmallFont1_end

.align 2, 0x00
glabel _gTextureSmallFont2
.incbin "textures/standalone/small_letter_2.ia16.mio0"
glabel _gTextureSmallFont2_end

.align 2, 0x00
glabel _gTextureSmallFont3
.incbin "textures/standalone/small_letter_3.ia16.mio0"
glabel _gTextureSmallFont3_end

.align 2, 0x00
glabel _gTextureSmallFont4
.incbin "textures/standalone/small_letter_4.ia16.mio0"
glabel _gTextureSmallFont4_end

.align 2, 0x00
glabel _gTextureSmallFont5
.incbin "textures/standalone/small_letter_5.ia16.mio0"
glabel _gTextureSmallFont5_end

.align 2, 0x00
glabel _gTextureSmallFont6
.incbin "textures/standalone/small_letter_6.ia16.mio0"
glabel _gTextureSmallFont6_end

.align 2, 0x00
glabel _gTextureSmallFont7
.incbin "textures/standalone/small_letter_7.ia16.mio0"
glabel _gTextureSmallFont7_end

.align 2, 0x00
glabel _gTextureSmallFont8
.incbin "textures/standalone/small_letter_8.ia16.mio0"
glabel _gTextureSmallFont8_end

.align 2, 0x00
glabel _gTextureSmallFont9
.incbin "textures/standalone/small_letter_9.ia16.mio0"
glabel _gTextureSmallFont9_end

.align 2, 0x00
glabel _gTextureN64ControllerPakDataSelect
.incbin "textures/standalone/n64_controller_pak_data_select.ia16.mio0"
glabel _gTextureN64ControllerPakDataSelect_end

.align 2, 0x00
glabel _gTextureEraseDataRecordConfirmation
.incbin "textures/standalone/erase_data_record_confirmation.ia16.mio0"
glabel _gTextureEraseDataRecordConfirmation_end

.align 2, 0x00
glabel _gTextureRecordNotErased
.incbin "textures/standalone/record_not_erased.ia16.mio0"
glabel _gTextureRecordNotErased_end

.align 2, 0x00
glabel _gTexturePlaceN64ControllerPakIntoController1
.incbin "textures/standalone/place_n64_controller_pak_into_controller_1.ia16.mio0"
glabel _gTexturePlaceN64ControllerPakIntoController1_end

.align 2, 0x00
glabel _gTexturePleaseReinsertOriginalN64ControllerPak
.incbin "textures/standalone/please_reinsert_original_n64_controller_pak.ia16.mio0"
glabel _gTexturePleaseReinsertOriginalN64ControllerPak_end

.align 2, 0x00
glabel _gTextureErasingSelectedRecord
.incbin "textures/standalone/erasing_selected_record.ia16.mio0"
glabel _gTextureErasingSelectedRecord_end

.align 2, 0x00
glabel _gTextureSelectRecord
.incbin "textures/standalone/select_record.ia16.mio0"
glabel _gTextureSelectRecord_end

.align 2, 0x00
glabel _gTextureTextEnd
.incbin "textures/standalone/text_end.ia16.mio0"
glabel _gTextureTextEnd_end

.align 2, 0x00
glabel _gTextureTableOfContents
.incbin "textures/standalone/table_of_contents.ia16.mio0"
glabel _gTextureTableOfContents_end

.align 2, 0x00
glabel _gTextureTextHash
.incbin "textures/standalone/text_hash.ia16.mio0"
glabel _gTextureTextHash_end

.align 2, 0x00
glabel _gTextureTextGameData
.incbin "textures/standalone/text_game_data.ia16.mio0"
glabel _gTextureTextGameData_end

.align 2, 0x00
glabel _gTextureTextPages
.incbin "textures/standalone/text_pages.ia16.mio0"
glabel _gTextureTextPages_end

.align 2, 0x00
glabel _gTextureTextPagesFree
.incbin "textures/standalone/text_pages_free.ia16.mio0"
glabel _gTextureTextPagesFree_end

.align 2, 0x00
glabel _gTextureTextErase
.incbin "textures/standalone/text_erase.ia16.mio0"
glabel _gTextureTextErase_end

.align 2, 0x00
glabel _gTextureTextQuit
.incbin "textures/standalone/text_quit.ia16.mio0"
glabel _gTextureTextQuit_end

.align 2, 0x00
glabel _gTexture7ED058
.incbin "textures/standalone/texture_7ED058.ia16.mio0"
glabel _gTexture7ED058_end

.align 2, 0x00
glabel _gTexture7ED290
.incbin "textures/standalone/texture_7ED290.ia16.mio0"
glabel _gTexture7ED290_end

.align 2, 0x00
glabel _gTexture7ED50C
.incbin "textures/standalone/texture_7ED50C.ia16.mio0"
glabel _gTexture7ED50C_end

.align 2, 0x00
glabel _gTexture7ED6A4
.incbin "textures/standalone/texture_7ED6A4.ia16.mio0"
glabel _gTexture7ED6A4_end

.align 2, 0x00
glabel _gTextureTinyFont0
.incbin "textures/standalone/tiny_font_0.ia16.mio0"
glabel _gTextureTinyFont0_end

.align 2, 0x00
glabel _gTextureTinyFont1
.incbin "textures/standalone/tiny_font_1.ia16.mio0"
glabel _gTextureTinyFont1_end

.align 2, 0x00
glabel _gTextureTinyFont2
.incbin "textures/standalone/tiny_font_2.ia16.mio0"
glabel _gTextureTinyFont2_end

.align 2, 0x00
glabel _gTextureTinyFont3
.incbin "textures/standalone/tiny_font_3.ia16.mio0"
glabel _gTextureTinyFont3_end

.align 2, 0x00
glabel _gTextureTinyFont4
.incbin "textures/standalone/tiny_font_4.ia16.mio0"
glabel _gTextureTinyFont4_end

.align 2, 0x00
glabel _gTextureTinyFont5
.incbin "textures/standalone/tiny_font_5.ia16.mio0"
glabel _gTextureTinyFont5_end

.align 2, 0x00
glabel _gTextureTinyFont6
.incbin "textures/standalone/tiny_font_6.ia16.mio0"
glabel _gTextureTinyFont6_end

.align 2, 0x00
glabel _gTextureTinyFont7
.incbin "textures/standalone/tiny_font_7.ia16.mio0"
glabel _gTextureTinyFont7_end

.align 2, 0x00
glabel _gTextureTinyFont8
.incbin "textures/standalone/tiny_font_8.ia16.mio0"
glabel _gTextureTinyFont8_end

.align 2, 0x00
glabel _gTextureTinyFont9
.incbin "textures/standalone/tiny_font_9.ia16.mio0"
glabel _gTextureTinyFont9_end

.align 2, 0x00
glabel _gTextureTinyFontA
.incbin "textures/standalone/tiny_font_A.ia16.mio0"
glabel _gTextureTinyFontA_end

.align 2, 0x00
glabel _gTextureTinyFontB
.incbin "textures/standalone/tiny_font_B.ia16.mio0"
glabel _gTextureTinyFontB_end

.align 2, 0x00
glabel _gTextureTinyFontC
.incbin "textures/standalone/tiny_font_C.ia16.mio0"
glabel _gTextureTinyFontC_end

.align 2, 0x00
glabel _gTextureTinyFontD
.incbin "textures/standalone/tiny_font_D.ia16.mio0"
glabel _gTextureTinyFontD_end

.align 2, 0x00
glabel _gTextureTinyFontE
.incbin "textures/standalone/tiny_font_E.ia16.mio0"
glabel _gTextureTinyFontE_end

.align 2, 0x00
glabel _gTextureTinyFontF
.incbin "textures/standalone/tiny_font_F.ia16.mio0"
glabel _gTextureTinyFontF_end

.align 2, 0x00
glabel _gTextureTinyFontG
.incbin "textures/standalone/tiny_font_G.ia16.mio0"
glabel _gTextureTinyFontG_end

.align 2, 0x00
glabel _gTextureTinyFontH
.incbin "textures/standalone/tiny_font_H.ia16.mio0"
glabel _gTextureTinyFontH_end

.align 2, 0x00
glabel _gTextureTinyFontI
.incbin "textures/standalone/tiny_font_I.ia16.mio0"
glabel _gTextureTinyFontI_end

.align 2, 0x00
glabel _gTextureTinyFontJ
.incbin "textures/standalone/tiny_font_J.ia16.mio0"
glabel _gTextureTinyFontJ_end

.align 2, 0x00
glabel _gTextureTinyFontK
.incbin "textures/standalone/tiny_font_K.ia16.mio0"
glabel _gTextureTinyFontK_end

.align 2, 0x00
glabel _gTextureTinyFontL
.incbin "textures/standalone/tiny_font_L.ia16.mio0"
glabel _gTextureTinyFontL_end

.align 2, 0x00
glabel _gTextureTinyFontM
.incbin "textures/standalone/tiny_font_M.ia16.mio0"
glabel _gTextureTinyFontM_end

.align 2, 0x00
glabel _gTextureTinyFontN
.incbin "textures/standalone/tiny_font_N.ia16.mio0"
glabel _gTextureTinyFontN_end

.align 2, 0x00
glabel _gTextureTinyFontO
.incbin "textures/standalone/tiny_font_O.ia16.mio0"
glabel _gTextureTinyFontO_end

.align 2, 0x00
glabel _gTextureTinyFontP
.incbin "textures/standalone/tiny_font_P.ia16.mio0"
glabel _gTextureTinyFontP_end

.align 2, 0x00
glabel _gTextureTinyFontQ
.incbin "textures/standalone/tiny_font_Q.ia16.mio0"
glabel _gTextureTinyFontQ_end

.align 2, 0x00
glabel _gTextureTinyFontR
.incbin "textures/standalone/tiny_font_R.ia16.mio0"
glabel _gTextureTinyFontR_end

.align 2, 0x00
glabel _gTextureTinyFontS
.incbin "textures/standalone/tiny_font_S.ia16.mio0"
glabel _gTextureTinyFontS_end

.align 2, 0x00
glabel _gTextureTinyFontT
.incbin "textures/standalone/tiny_font_T.ia16.mio0"
glabel _gTextureTinyFontT_end

.align 2, 0x00
glabel _gTextureTinyFontU
.incbin "textures/standalone/tiny_font_U.ia16.mio0"
glabel _gTextureTinyFontU_end

.align 2, 0x00
glabel _gTextureTinyFontV
.incbin "textures/standalone/tiny_font_V.ia16.mio0"
glabel _gTextureTinyFontV_end

.align 2, 0x00
glabel _gTextureTinyFontW
.incbin "textures/standalone/tiny_font_W.ia16.mio0"
glabel _gTextureTinyFontW_end

.align 2, 0x00
glabel _gTextureTinyFontX
.incbin "textures/standalone/tiny_font_X.ia16.mio0"
glabel _gTextureTinyFontX_end

.align 2, 0x00
glabel _gTextureTinyFontY
.incbin "textures/standalone/tiny_font_Y.ia16.mio0"
glabel _gTextureTinyFontY_end

.align 2, 0x00
glabel _gTextureTinyFontZ
.incbin "textures/standalone/tiny_font_Z.ia16.mio0"
glabel _gTextureTinyFontZ_end

.align 2, 0x00
glabel _gTextureTinyFontExclamationMark
.incbin "textures/standalone/tiny_font_exclamation_mark.ia16.mio0"
glabel _gTextureTinyFontExclamationMark_end

.align 2, 0x00
glabel _gTextureTinyFontDoubleQuote
.incbin "textures/standalone/tiny_font_double_quote.ia16.mio0"
glabel _gTextureTinyFontDoubleQuote_end

.align 2, 0x00
glabel _gTextureTinyFontHash
.incbin "textures/standalone/tiny_font_hash.ia16.mio0"
glabel _gTextureTinyFontHash_end

.align 2, 0x00
glabel _gTextureTinyFontSingleQuote
.incbin "textures/standalone/tiny_font_single_quote.ia16.mio0"
glabel _gTextureTinyFontSingleQuote_end

.align 2, 0x00
glabel _gTextureTinyFontAsterisk
.incbin "textures/standalone/tiny_font_asterisk.ia16.mio0"
glabel _gTextureTinyFontAsterisk_end

.align 2, 0x00
glabel _gTextureTinyFontPlus
.incbin "textures/standalone/tiny_font_plus.ia16.mio0"
glabel _gTextureTinyFontPlus_end

.align 2, 0x00
glabel _gTexture7EEB18
.incbin "textures/standalone/texture_7EEB18.ia16.mio0"
glabel _gTexture7EEB18_end

.align 2, 0x00
glabel _gTextureTinyFontMinus
.incbin "textures/standalone/tiny_font_minus.ia16.mio0"
glabel _gTextureTinyFontMinus_end

.align 2, 0x00
glabel _gTextureTinyFontComma
.incbin "textures/standalone/tiny_font_comma.ia16.mio0"
glabel _gTextureTinyFontComma_end

.align 2, 0x00
glabel _gTextureTinyFontForwardSlash
.incbin "textures/standalone/tiny_font_forward_slash.ia16.mio0"
glabel _gTextureTinyFontForwardSlash_end

.align 2, 0x00
glabel _gTextureTinyFontColon
.incbin "textures/standalone/tiny_font_colon.ia16.mio0"
glabel _gTextureTinyFontColon_end

.align 2, 0x00
glabel _gTexture7EEC34
.incbin "textures/standalone/texture_7EEC34.ia16.mio0"
glabel _gTexture7EEC34_end

.align 2, 0x00
glabel _gTextureTinyFontQuestion
.incbin "textures/standalone/tiny_font_question.ia16.mio0"
glabel _gTextureTinyFontQuestion_end

.align 2, 0x00
glabel _gTexture7EECE4
.incbin "textures/standalone/texture_7EECE4.ia16.mio0"
glabel _gTexture7EECE4_end

.align 2, 0x00
glabel _gTexture7EED74
.incbin "textures/standalone/texture_7EED74.ia16.mio0"
glabel _gTexture7EED74_end

.align 2, 0x00
glabel _gTexture7EEDB0
.incbin "textures/standalone/texture_7EEDB0.ia16.mio0"
glabel _gTexture7EEDB0_end

.align 2, 0x00
glabel _gTexture7EEDE8
.incbin "textures/standalone/texture_7EEDE8.ia16.mio0"
glabel _gTexture7EEDE8_end

.align 2, 0x00
glabel _gTexture7EEE20
.incbin "textures/standalone/texture_7EEE20.ia16.mio0"
glabel _gTexture7EEE20_end

.align 2, 0x00
glabel _gTexture7EEE7C
.incbin "textures/standalone/texture_7EEE7C.ia16.mio0"
glabel _gTexture7EEE7C_end

.align 2, 0x00
glabel _gTexture7EEED0
.incbin "textures/standalone/texture_7EEED0.ia16.mio0"
glabel _gTexture7EEED0_end

.align 2, 0x00
glabel _gTexture7EEF3C
.incbin "textures/standalone/texture_7EEF3C.ia16.mio0"
glabel _gTexture7EEF3C_end

.align 2, 0x00
glabel _gTexture7EEF90
.incbin "textures/standalone/texture_7EEF90.ia16.mio0"
glabel _gTexture7EEF90_end

.align 2, 0x00
glabel _gTexture7EEFF4
.incbin "textures/standalone/texture_7EEFF4.ia16.mio0"
glabel _gTexture7EEFF4_end

.align 2, 0x00
glabel _gTexture7EF058
.incbin "textures/standalone/texture_7EF058.ia16.mio0"
glabel _gTexture7EF058_end

.align 2, 0x00
glabel _gTexture7EF0B4
.incbin "textures/standalone/texture_7EF0B4.ia16.mio0"
glabel _gTexture7EF0B4_end

.align 2, 0x00
glabel _gTexture7EF110
.incbin "textures/standalone/texture_7EF110.ia16.mio0"
glabel _gTexture7EF110_end

.align 2, 0x00
glabel _gTexture7EF17C
.incbin "textures/standalone/texture_7EF17C.ia16.mio0"
glabel _gTexture7EF17C_end

.align 2, 0x00
glabel _gTexture7EF1F0
.incbin "textures/standalone/texture_7EF1F0.ia16.mio0"
glabel _gTexture7EF1F0_end

.align 2, 0x00
glabel _gTexture7EF250
.incbin "textures/standalone/texture_7EF250.ia16.mio0"
glabel _gTexture7EF250_end

.align 2, 0x00
glabel _gTexture7EF2B8
.incbin "textures/standalone/texture_7EF2B8.ia16.mio0"
glabel _gTexture7EF2B8_end

.align 2, 0x00
glabel _gTexture7EF314
.incbin "textures/standalone/texture_7EF314.ia16.mio0"
glabel _gTexture7EF314_end

.align 2, 0x00
glabel _gTexture7EF388
.incbin "textures/standalone/texture_7EF388.ia16.mio0"
glabel _gTexture7EF388_end

.align 2, 0x00
glabel _gTexture7EF3F8
.incbin "textures/standalone/texture_7EF3F8.ia16.mio0"
glabel _gTexture7EF3F8_end

.align 2, 0x00
glabel _gTexture7EF470
.incbin "textures/standalone/texture_7EF470.ia16.mio0"
glabel _gTexture7EF470_end

.align 2, 0x00
glabel _gTexture7EF4E4
.incbin "textures/standalone/texture_7EF4E4.ia16.mio0"
glabel _gTexture7EF4E4_end

.align 2, 0x00
glabel _gTexture7EF554
.incbin "textures/standalone/texture_7EF554.ia16.mio0"
glabel _gTexture7EF554_end

.align 2, 0x00
glabel _gTexture7EF5C0
.incbin "textures/standalone/texture_7EF5C0.ia16.mio0"
glabel _gTexture7EF5C0_end

.align 2, 0x00
glabel _gTexture7EF620
.incbin "textures/standalone/texture_7EF620.ia16.mio0"
glabel _gTexture7EF620_end

.align 2, 0x00
glabel _gTexture7EF694
.incbin "textures/standalone/texture_7EF694.ia16.mio0"
glabel _gTexture7EF694_end

.align 2, 0x00
glabel _gTexture7EF708
.incbin "textures/standalone/texture_7EF708.ia16.mio0"
glabel _gTexture7EF708_end

.align 2, 0x00
glabel _gTexture7EF77C
.incbin "textures/standalone/texture_7EF77C.ia16.mio0"
glabel _gTexture7EF77C_end

.align 2, 0x00
glabel _gTexture7EF7E8
.incbin "textures/standalone/texture_7EF7E8.ia16.mio0"
glabel _gTexture7EF7E8_end

.align 2, 0x00
glabel _gTexture7EF85C
.incbin "textures/standalone/texture_7EF85C.ia16.mio0"
glabel _gTexture7EF85C_end

.align 2, 0x00
glabel _gTexture7EF8C8
.incbin "textures/standalone/texture_7EF8C8.ia16.mio0"
glabel _gTexture7EF8C8_end

.align 2, 0x00
glabel _gTexture7EF93C
.incbin "textures/standalone/texture_7EF93C.ia16.mio0"
glabel _gTexture7EF93C_end

.align 2, 0x00
glabel _gTexture7EF9B4
.incbin "textures/standalone/texture_7EF9B4.ia16.mio0"
glabel _gTexture7EF9B4_end

.align 2, 0x00
glabel _gTexture7EFA2C
.incbin "textures/standalone/texture_7EFA2C.ia16.mio0"
glabel _gTexture7EFA2C_end

.align 2, 0x00
glabel _gTexture7EFAA8
.incbin "textures/standalone/texture_7EFAA8.ia16.mio0"
glabel _gTexture7EFAA8_end

.align 2, 0x00
glabel _gTexture7EFB00
.incbin "textures/standalone/texture_7EFB00.ia16.mio0"
glabel _gTexture7EFB00_end

.align 2, 0x00
glabel _gTexture7EFB64
.incbin "textures/standalone/texture_7EFB64.ia16.mio0"
glabel _gTexture7EFB64_end

.align 2, 0x00
glabel _gTexture7EFBBC
.incbin "textures/standalone/texture_7EFBBC.ia16.mio0"
glabel _gTexture7EFBBC_end

.align 2, 0x00
glabel _gTexture7EFC30
.incbin "textures/standalone/texture_7EFC30.ia16.mio0"
glabel _gTexture7EFC30_end

.align 2, 0x00
glabel _gTexture7EFCAC
.incbin "textures/standalone/texture_7EFCAC.ia16.mio0"
glabel _gTexture7EFCAC_end

.align 2, 0x00
glabel _gTexture7EFD00
.incbin "textures/standalone/texture_7EFD00.ia16.mio0"
glabel _gTexture7EFD00_end

.align 2, 0x00
glabel _gTexture7EFD60
.incbin "textures/standalone/texture_7EFD60.ia16.mio0"
glabel _gTexture7EFD60_end

.align 2, 0x00
glabel _gTexture7EFDD4
.incbin "textures/standalone/texture_7EFDD4.ia16.mio0"
glabel _gTexture7EFDD4_end

.align 2, 0x00
glabel _gTexture7EFE48
.incbin "textures/standalone/texture_7EFE48.ia16.mio0"
glabel _gTexture7EFE48_end

.align 2, 0x00
glabel _gTexture7EFEA0
.incbin "textures/standalone/texture_7EFEA0.ia16.mio0"
glabel _gTexture7EFEA0_end

.align 2, 0x00
glabel _gTexture7EFF2C
.incbin "textures/standalone/texture_7EFF2C.ia16.mio0"
glabel _gTexture7EFF2C_end

.align 2, 0x00
glabel _gTexture7EFF90
.incbin "textures/standalone/texture_7EFF90.ia16.mio0"
glabel _gTexture7EFF90_end

.align 2, 0x00
glabel _gTexture7F0000
.incbin "textures/standalone/texture_7F0000.ia16.mio0"
glabel _gTexture7F0000_end

.align 2, 0x00
glabel _gTexture7F006C
.incbin "textures/standalone/texture_7F006C.ia16.mio0"
glabel _gTexture7F006C_end

.align 2, 0x00
glabel _gTexture7F00D8
.incbin "textures/standalone/texture_7F00D8.ia16.mio0"
glabel _gTexture7F00D8_end

.align 2, 0x00
glabel _gTexture7F0158
.incbin "textures/standalone/texture_7F0158.ia16.mio0"
glabel _gTexture7F0158_end

.align 2, 0x00
glabel _gTexture7F01D0
.incbin "textures/standalone/texture_7F01D0.ia16.mio0"
glabel _gTexture7F01D0_end

.align 2, 0x00
glabel _gTexture7F023C
.incbin "textures/standalone/texture_7F023C.ia16.mio0"
glabel _gTexture7F023C_end

.align 2, 0x00
glabel _gTexture7F02B4
.incbin "textures/standalone/texture_7F02B4.ia16.mio0"
glabel _gTexture7F02B4_end

.align 2, 0x00
glabel _gTexture7F032C
.incbin "textures/standalone/texture_7F032C.ia16.mio0"
glabel _gTexture7F032C_end

.align 2, 0x00
glabel _gTexture7F0390
.incbin "textures/standalone/texture_7F0390.ia16.mio0"
glabel _gTexture7F0390_end

.align 2, 0x00
glabel _gTexture7F0404
.incbin "textures/standalone/texture_7F0404.ia16.mio0"
glabel _gTexture7F0404_end

.align 2, 0x00
glabel _gTexture7F0470
.incbin "textures/standalone/texture_7F0470.ia16.mio0"
glabel _gTexture7F0470_end

.align 2, 0x00
glabel _gTexture7F04EC
.incbin "textures/standalone/texture_7F04EC.ia16.mio0"
glabel _gTexture7F04EC_end

.align 2, 0x00
glabel _gTexture7F055C
.incbin "textures/standalone/texture_7F055C.ia16.mio0"
glabel _gTexture7F055C_end

.align 2, 0x00
glabel _gTexture7F05F0
.incbin "textures/standalone/texture_7F05F0.ia16.mio0"
glabel _gTexture7F05F0_end

.align 2, 0x00
glabel _gTexture7F0670
.incbin "textures/standalone/texture_7F0670.ia16.mio0"
glabel _gTexture7F0670_end

.align 2, 0x00
glabel _gTexture7F06EC
.incbin "textures/standalone/texture_7F06EC.ia16.mio0"
glabel _gTexture7F06EC_end

.align 2, 0x00
glabel _gTexture7F0768
.incbin "textures/standalone/texture_7F0768.ia16.mio0"
glabel _gTexture7F0768_end

.align 2, 0x00
glabel _gTexture7F07E0
.incbin "textures/standalone/texture_7F07E0.ia16.mio0"
glabel _gTexture7F07E0_end

.align 2, 0x00
glabel _gTexture7F0858
.incbin "textures/standalone/texture_7F0858.ia16.mio0"
glabel _gTexture7F0858_end

.align 2, 0x00
glabel _gTexture7F08D8
.incbin "textures/standalone/texture_7F08D8.ia16.mio0"
glabel _gTexture7F08D8_end

.align 2, 0x00
glabel _gTexture7F0948
.incbin "textures/standalone/texture_7F0948.ia16.mio0"
glabel _gTexture7F0948_end

.align 2, 0x00
glabel _gTexture7F09D0
.incbin "textures/standalone/texture_7F09D0.ia16.mio0"
glabel _gTexture7F09D0_end

.align 2, 0x00
glabel _gTexture7F0A3C
.incbin "textures/standalone/texture_7F0A3C.ia16.mio0"
glabel _gTexture7F0A3C_end

.align 2, 0x00
glabel _gTexture7F0ABC
.incbin "textures/standalone/texture_7F0ABC.ia16.mio0"
glabel _gTexture7F0ABC_end

.align 2, 0x00
glabel _gTexture7F0B34
.incbin "textures/standalone/texture_7F0B34.ia16.mio0"
glabel _gTexture7F0B34_end

.align 2, 0x00
glabel _gTexture7F0BB0
.incbin "textures/standalone/texture_7F0BB0.ia16.mio0"
glabel _gTexture7F0BB0_end

.align 2, 0x00
glabel _gTexture7F0C24
.incbin "textures/standalone/texture_7F0C24.ia16.mio0"
glabel _gTexture7F0C24_end

.align 2, 0x00
glabel _gTexture7F0C94
.incbin "textures/standalone/texture_7F0C94.ia16.mio0"
glabel _gTexture7F0C94_end

.align 2, 0x00
glabel _gTexture7F0D0C
.incbin "textures/standalone/texture_7F0D0C.ia16.mio0"
glabel _gTexture7F0D0C_end

.align 2, 0x00
glabel _gTexture7F0D8C
.incbin "textures/standalone/texture_7F0D8C.ia16.mio0"
glabel _gTexture7F0D8C_end

.align 2, 0x00
glabel _gTexture7F0DEC
.incbin "textures/standalone/texture_7F0DEC.ia16.mio0"
glabel _gTexture7F0DEC_end

.align 2, 0x00
glabel _gTexture7F0E5C
.incbin "textures/standalone/texture_7F0E5C.ia16.mio0"
glabel _gTexture7F0E5C_end

.align 2, 0x00
glabel _gTexture7F0EE4
.incbin "textures/standalone/texture_7F0EE4.ia16.mio0"
glabel _gTexture7F0EE4_end

.align 2, 0x00
glabel _gTexture7F0F5C
.incbin "textures/standalone/texture_7F0F5C.ia16.mio0"
glabel _gTexture7F0F5C_end

.align 2, 0x00
glabel _gTexture7F0FD8
.incbin "textures/standalone/texture_7F0FD8.ia16.mio0"
glabel _gTexture7F0FD8_end

.align 2, 0x00
glabel _gTexture7F1038
.incbin "textures/standalone/texture_7F1038.ia16.mio0"
glabel _gTexture7F1038_end

.align 2, 0x00
glabel _gTexture7F109C
.incbin "textures/standalone/texture_7F109C.ia16.mio0"
glabel _gTexture7F109C_end

.align 2, 0x00
glabel _gTexture7F1124
.incbin "textures/raw/7F1124.i4"

.align 2, 0x00
glabel _gTexture7F11F4
.incbin "textures/raw/7F11F4.i4"

.align 2, 0x00
glabel _gTexture7F12C4
.incbin "textures/raw/7F12C4.i4"

.align 2, 0x00
glabel _gTexture7F1394
.incbin "textures/raw/7F1394.i4"

.align 2, 0x00
glabel _gTexture7F1464
.incbin "textures/raw/7F1464.i4"

.align 2, 0x00
glabel _gTexture7F1534
.incbin "textures/raw/7F1534.i4"

.align 2, 0x00
glabel _gTexture7F1604
.incbin "textures/raw/7F1604.i4"

.align 2, 0x00
glabel _gTexture7F16D4
.incbin "textures/raw/7F16D4.i4"

.align 2, 0x00
glabel _gTexture7F17A4
.incbin "textures/raw/7F17A4.i4"

.align 2, 0x00
glabel _gTexture7F1874
.incbin "textures/raw/7F1874.i4"

.align 2, 0x00
glabel _gTexture7F1944
.incbin "textures/raw/7F1944.i4"

.align 2, 0x00
glabel _gTexture7F1A14
.incbin "textures/raw/7F1A14.i4"

.align 2, 0x00
glabel _gTexture7F1AE4
.incbin "textures/raw/7F1AE4.i4"

.align 2, 0x00
glabel _gTexture7F1BB4
.incbin "textures/raw/7F1BB4.i4"

.align 2, 0x00
glabel _gTexture7F1C84
.incbin "textures/raw/7F1C84.i4"

.align 2, 0x00
glabel _gTexture7F1D54
.incbin "textures/raw/7F1D54.i4"

.align 2, 0x00
glabel _gTexture7F1E24
.incbin "textures/raw/7F1E24.i4"

.align 2, 0x00
glabel _gTexture7F1EF4
.incbin "textures/raw/7F1EF4.i4"

.align 2, 0x00
glabel _gTexture7F1FC4
.incbin "textures/raw/7F1FC4.i4"

.align 2, 0x00
glabel _gTexture7F2094
.incbin "textures/raw/7F2094.i4"

.align 2, 0x00
glabel _gTexture7F2164
.incbin "textures/raw/7F2164.i4"

.align 2, 0x00
glabel _gTexture7F2234
.incbin "textures/raw/7F2234.i4"

.align 2, 0x00
glabel _gTexture7F2304
.incbin "textures/raw/7F2304.i4"

.align 2, 0x00
glabel _gTexture7F23D4
.incbin "textures/raw/7F23D4.i4"

.align 2, 0x00
glabel _gTexture7F24A4
.incbin "textures/raw/7F24A4.i4"

.align 2, 0x00
glabel _gTexture7F2574
.incbin "textures/raw/7F2574.i4"

.align 2, 0x00
glabel _gTexture7F2644
.incbin "textures/raw/7F2644.i4"

.align 2, 0x00
glabel _gTexture7F2714
.incbin "textures/raw/7F2714.i4"

.align 2, 0x00
glabel _gTexture7F27E4
.incbin "textures/raw/7F27E4.i4"

.align 2, 0x00
glabel _gTexture7F28B4
.incbin "textures/raw/7F28B4.i4"

.align 2, 0x00
glabel _gTexture7F2984
.incbin "textures/raw/7F2984.i4"

.align 2, 0x00
glabel _gTexture7F2A54
.incbin "textures/raw/7F2A54.i4"

.align 2, 0x00
glabel _gTexture7F2B24
.incbin "textures/raw/7F2B24.i4"

.align 2, 0x00
glabel _gTexture7F2BF4
.incbin "textures/raw/7F2BF4.i4"

.align 2, 0x00
glabel _gTexture7F2CC4
.incbin "textures/raw/7F2CC4.i4"

.align 2, 0x00
glabel _gTexture7F2D94
.incbin "textures/raw/7F2D94.i4"

.align 2, 0x00
glabel _gTexture7F2E64
.incbin "textures/raw/7F2E64.i4"

.align 2, 0x00
glabel _gTexture7F2F34
.incbin "textures/raw/7F2F34.i4"

.align 2, 0x00
glabel _gTexture7F3004
.incbin "textures/raw/7F3004.i4"

.align 2, 0x00
glabel _gTexture7F30D4
.incbin "textures/raw/7F30D4.i4"

.align 2, 0x00
glabel _gTexture7F31A4
.incbin "textures/raw/7F31A4.i4"

.align 2, 0x00
glabel _gTexture7F3274
.incbin "textures/raw/7F3274.i4"

.align 2, 0x00
glabel _gTexture7F3344
.incbin "textures/raw/7F3344.i4"

.align 2, 0x00
glabel _gTexture7F3414
.incbin "textures/raw/7F3414.i4"

.align 2, 0x00
glabel _gTexture7F34E4
.incbin "textures/raw/7F34E4.i4"

.align 2, 0x00
glabel _gTexture7F35B4
.incbin "textures/raw/7F35B4.i4"

.align 2, 0x00
glabel _gTexture7F3634
.incbin "textures/raw/7F3634.i4"

.align 2, 0x00
glabel _gTexture7F36B4
.incbin "textures/raw/7F36B4.i4"

.align 2, 0x00
glabel _gTexture7F3734
.incbin "textures/raw/7F3734.i4"

.align 2, 0x00
glabel _gTexture7F37B4
.incbin "textures/raw/7F37B4.i4"

.align 2, 0x00
glabel _gTexture7F3834
.incbin "textures/raw/7F3834.i4"

.align 2, 0x00
glabel _gTexture7F38B4
.incbin "textures/raw/7F38B4.i4"

.align 2, 0x00
glabel _gTexture7F3934
.incbin "textures/raw/7F3934.i4"

.align 2, 0x00
glabel _gTexture7F39B4
.incbin "textures/raw/7F39B4.i4"

.align 2, 0x00
glabel _gTexture7F3A34
.incbin "textures/raw/7F3A34.i4"

.align 2, 0x00
glabel _gTexture7F3AB4
.incbin "textures/raw/7F3AB4.i4"

.align 2, 0x00
glabel _gTexture7F3B34
.incbin "textures/raw/7F3B34.i4"

.align 2, 0x00
glabel _gTexture7F3BB4
.incbin "textures/raw/7F3BB4.i4"

.align 2, 0x00
glabel _gTexture7F3C34
.incbin "textures/raw/7F3C34.i4"

.align 2, 0x00
glabel _gTexture7F3CB4
.incbin "textures/raw/7F3CB4.i4"

.align 2, 0x00
glabel _gTexture7F3D34
.incbin "textures/raw/7F3D34.i4"

.align 2, 0x00
glabel _gTexture7F3DB4
.incbin "textures/raw/7F3DB4.i4"

.align 2, 0x00
glabel _gTexture7F3E34
.incbin "textures/raw/7F3E34.i4"

.align 2, 0x00
glabel _gTexture7F3EB4
.incbin "textures/raw/7F3EB4.i4"

.align 2, 0x00
glabel _gTexture7F3F34
.incbin "textures/raw/7F3F34.i4"

.align 2, 0x00
glabel _gTexture7F3FB4
.incbin "textures/raw/7F3FB4.i4"

.align 2, 0x00
glabel _gTexture7F4034
.incbin "textures/raw/7F4034.i4"

.align 2, 0x00
glabel _gTexture7F40B4
.incbin "textures/raw/7F40B4.i4"

.align 2, 0x00
glabel _gTexture7F4134
.incbin "textures/raw/7F4134.i4"

.align 2, 0x00
glabel _gTexture7F41B4
.incbin "textures/raw/7F41B4.i4"

.align 2, 0x00
glabel _gTexture7F4234
.incbin "textures/raw/7F4234.i4"

.align 2, 0x00
glabel _gTexture7F42B4
.incbin "textures/raw/7F42B4.i4"

.align 2, 0x00
glabel _gTexture7F4334
.incbin "textures/raw/7F4334.i4"

.align 2, 0x00
glabel _gTexture7F43B4
.incbin "textures/raw/7F43B4.i4"

.align 2, 0x00
glabel _gTexture7F4434
.incbin "textures/raw/7F4434.i4"

.align 2, 0x00
glabel _gTexture7F44B4
.incbin "textures/raw/7F44B4.i4"

.align 2, 0x00
glabel _gTexture7F4534
.incbin "textures/raw/7F4534.i4"

.align 2, 0x00
glabel _gTexture7F45B4
.incbin "textures/raw/7F45B4.i4"

.align 2, 0x00
glabel _gTexture7F4634
.incbin "textures/raw/7F4634.i4"

.align 2, 0x00
glabel _gTexture7F46B4
.incbin "textures/raw/7F46B4.i4"

.align 2, 0x00
glabel _gTexture7F4734
.incbin "textures/raw/7F4734.i4"

.align 2, 0x00
glabel _gTexture7F47B4
.incbin "textures/raw/7F47B4.i4"

.align 2, 0x00
glabel _gTexture7F4834
.incbin "textures/raw/7F4834.i4"

.align 2, 0x00
glabel _gTexture7F48B4
.incbin "textures/raw/7F48B4.i4"

.align 2, 0x00
glabel _gTexture7F4934
.incbin "textures/raw/7F4934.i4"

.align 2, 0x00
glabel _gTexture7F49B4
.incbin "textures/raw/7F49B4.i4"

.align 2, 0x00
glabel _gTexture7F4A34
.incbin "textures/raw/7F4A34.i4"

.align 2, 0x00
glabel _gTexture7F4AB4
.incbin "textures/raw/7F4AB4.i4"

.align 2, 0x00
glabel _gTexture7F4B34
.incbin "textures/raw/7F4B34.i4"

.align 2, 0x00
glabel _gTexture7F4BB4
.incbin "textures/raw/7F4BB4.i4"

.align 2, 0x00
glabel _gTexture7F4C34
.incbin "textures/raw/7F4C34.i4"

.align 2, 0x00
glabel _gTexture7F4CB4
.incbin "textures/raw/7F4CB4.i4"

.align 2, 0x00
glabel _gTexture7F4D34
.incbin "textures/raw/7F4D34.i4"

.align 2, 0x00
glabel _gTexture7F4DB4
.incbin "textures/raw/7F4DB4.i4"

.align 2, 0x00
glabel _gTexture7F4E34
.incbin "textures/raw/7F4E34.i4"

.align 2, 0x00
glabel _gTexture7F4EB4
.incbin "textures/raw/7F4EB4.i4"

.align 2, 0x00
glabel _gTexture7F4F34
.incbin "textures/raw/7F4F34.i4"

.align 2, 0x00
glabel _gTexture7F4FB4
.incbin "textures/raw/7F4FB4.i4"

.align 2, 0x00
glabel _gTexture7F5034
.incbin "textures/raw/7F5034.i4"

.align 2, 0x00
glabel _gTexture7F50B4
.incbin "textures/raw/7F50B4.i4"

.align 2, 0x00
glabel _gTexture7F5134
.incbin "textures/raw/7F5134.i4"

.align 2, 0x00
glabel _gTexture7F51B4
.incbin "textures/raw/7F51B4.i4"

.align 2, 0x00
glabel _gTexture7F5234
.incbin "textures/raw/7F5234.i4"

.align 2, 0x00
glabel _gTexture7F52B4
.incbin "textures/raw/7F52B4.i4"

.align 2, 0x00
glabel _gTexture7F5334
.incbin "textures/raw/7F5334.i4"

.align 2, 0x00
glabel _gTexture7F53B4
.incbin "textures/raw/7F53B4.i4"

.align 2, 0x00
glabel _gTexture7F5434
.incbin "textures/raw/7F5434.i4"

.align 2, 0x00
glabel _gTexture7F54B4
.incbin "textures/raw/7F54B4.i4"

.align 2, 0x00
glabel _gTexture7F5534
.incbin "textures/raw/7F5534.i4"

.align 2, 0x00
glabel _gTexture7F55B4
.incbin "textures/raw/7F55B4.i4"

.align 2, 0x00
glabel _gTexture7F5634
.incbin "textures/raw/7F5634.i4"

.align 2, 0x00
glabel _gTexture7F56B4
.incbin "textures/raw/7F56B4.i4"

.align 2, 0x00
glabel _gTexture7F5734
.incbin "textures/raw/7F5734.i4"

.align 2, 0x00
glabel _gTexture7F57B4
.incbin "textures/raw/7F57B4.i4"

.align 2, 0x00
glabel _gTexture7F5834
.incbin "textures/raw/7F5834.i4"

.align 2, 0x00
glabel _gTexture7F58B4
.incbin "textures/raw/7F58B4.i4"

.align 2, 0x00
glabel _gTexture7F5934
.incbin "textures/raw/7F5934.i4"

.align 2, 0x00
glabel _gTexture7F59B4
.incbin "textures/raw/7F59B4.i4"

.align 2, 0x00
glabel _gTexture7F5A34
.incbin "textures/raw/7F5A34.i4"

.align 2, 0x00
glabel _gTexture7F5AB4
.incbin "textures/raw/7F5AB4.i4"

.align 2, 0x00
glabel _gTexture7F5B34
.incbin "textures/raw/7F5B34.i4"

.align 2, 0x00
glabel _gTexture7F5BB4
.incbin "textures/raw/7F5BB4.i4"

.align 2, 0x00
glabel _gTexture7F5C34
.incbin "textures/raw/7F5C34.i4"

.align 2, 0x00
glabel _gTexture7F5CB4
.incbin "textures/raw/7F5CB4.i4"

.align 2, 0x00
glabel _gTexture7F5D34
.incbin "textures/raw/7F5D34.i4"

.align 2, 0x00
glabel _gTexture7F5DB4
.incbin "textures/raw/7F5DB4.i4"

.align 2, 0x00
glabel _gTexture7F5E34
.incbin "textures/raw/7F5E34.i4"

.align 2, 0x00
glabel _gTexture7F5EB4
.incbin "textures/raw/7F5EB4.i4"

.align 2, 0x00
glabel _gTexture7F5F34
.incbin "textures/raw/7F5F34.i4"

.align 2, 0x00
glabel _gTexture7F5FB4
.incbin "textures/raw/7F5FB4.i4"

.align 2, 0x00
glabel _gTexture7F6034
.incbin "textures/raw/7F6034.i4"

.align 2, 0x00
glabel _gTexture7F60B4
.incbin "textures/raw/7F60B4.i4"

.align 2, 0x00
glabel _gTexture7F6134
.incbin "textures/raw/7F6134.i4"

.align 2, 0x00
glabel _gTexture7F61B4
.incbin "textures/raw/7F61B4.i4"

.align 2, 0x00
glabel _gTexture7F6234
.incbin "textures/raw/7F6234.i4"

.align 2, 0x00
glabel _gTexture7F62B4
.incbin "textures/raw/7F62B4.i4"

.align 2, 0x00
glabel _gTexture7F6334
.incbin "textures/raw/7F6334.i4"

.align 2, 0x00
glabel _gTexture7F63B4
.incbin "textures/raw/7F63B4.i4"

.align 2, 0x00
glabel _gTexture7F6434
.incbin "textures/raw/7F6434.i4"

.align 2, 0x00
glabel _gTexture7F64B4
.incbin "textures/raw/7F64B4.i4"

.align 2, 0x00
glabel _gTexture7F6534
.incbin "textures/raw/7F6534.i4"

.align 2, 0x00
glabel _gTexture7F65B4
.incbin "textures/raw/7F65B4.i4"

.align 2, 0x00
glabel _gTexture7F6634
.incbin "textures/raw/7F6634.i4"

.align 2, 0x00
glabel _gTexture7F66B4
.incbin "textures/raw/7F66B4.i4"

.align 2, 0x00
glabel _gTexture7F6734
.incbin "textures/raw/7F6734.i4"

.align 2, 0x00
glabel _gTexture7F67B4
.incbin "textures/raw/7F67B4.i4"

.align 2, 0x00
glabel _gTexture7F6834
.incbin "textures/raw/7F6834.i4"

.align 2, 0x00
glabel _gTexture7F68B4
.incbin "textures/raw/7F68B4.i4"

.align 2, 0x00
glabel _gTexture7F6934
.incbin "textures/raw/7F6934.i4"

.align 2, 0x00
glabel _gTexture7F69B4
.incbin "textures/raw/7F69B4.i4"

.align 2, 0x00
glabel _gTexture7F6A34
.incbin "textures/raw/7F6A34.i4"

.align 2, 0x00
glabel _gTexture7F6AB4
.incbin "textures/raw/7F6AB4.i4"

.align 2, 0x00
glabel _gTexture7F6B34
.incbin "textures/raw/7F6B34.i4"

.align 2, 0x00
glabel _gTexture7F6BB4
.incbin "textures/raw/7F6BB4.i4"

.align 2, 0x00
glabel _gTexture7F6C34
.incbin "textures/raw/7F6C34.i4"

.align 2, 0x00
glabel _gTexture7F6CB4
.incbin "textures/raw/7F6CB4.i4"

.align 2, 0x00
glabel _gTexture7F6D34
.incbin "textures/raw/7F6D34.i4"

.align 2, 0x00
glabel _gTexture7F6DB4
.incbin "textures/raw/7F6DB4.i4"

.align 2, 0x00
glabel _gTexture7F6E34
.incbin "textures/raw/7F6E34.i4"

.align 2, 0x00
glabel _gTexture7F6EB4
.incbin "textures/raw/7F6EB4.i4"

.align 2, 0x00
glabel _gTexture7F6F34
.incbin "textures/raw/7F6F34.i4"

.align 2, 0x00
glabel _gTexture7F6FB4
.incbin "textures/raw/7F6FB4.i4"

.align 2, 0x00
glabel _gTexture7F7034
.incbin "textures/raw/7F7034.i4"

.align 2, 0x00
glabel _gTexture7F70B4
.incbin "textures/raw/7F70B4.i4"

.align 2, 0x00
glabel _gTexture7F7134
.incbin "textures/raw/7F7134.i4"

.align 2, 0x00
glabel _gTexture7F71B4
.incbin "textures/raw/7F71B4.i4"

.align 2, 0x00
glabel _gTexture7F7234
.incbin "textures/raw/7F7234.i4"

.align 2, 0x00
glabel _gTexture7F72B4
.incbin "textures/raw/7F72B4.i4"

.align 2, 0x00
glabel _gTexture7F7334
.incbin "textures/raw/7F7334.i4"

.align 2, 0x00
glabel _gTexture7F73B4
.incbin "textures/raw/7F73B4.i4"

.align 2, 0x00
glabel _gTexture7F7434
.incbin "textures/raw/7F7434.i4"

.align 2, 0x00
glabel _gTexture7F74B4
.incbin "textures/raw/7F74B4.i4"

.align 2, 0x00
glabel _gTexture7F7534
.incbin "textures/raw/7F7534.i4"

.align 2, 0x00
glabel _gTexture7F75B4
.incbin "textures/raw/7F75B4.i4"

.align 2, 0x00
glabel _gTexture7F7634
.incbin "textures/raw/7F7634.i4"

.align 2, 0x00
glabel _gTexture7F76B4
.incbin "textures/raw/7F76B4.i4"

.align 2, 0x00
glabel _gTexture7F7734
.incbin "textures/raw/7F7734.i4"

.align 2, 0x00
glabel _gTexture7F77B4
.incbin "textures/raw/7F77B4.i4"

.align 2, 0x00
glabel _gTexture7F7834
.incbin "textures/raw/7F7834.i4"

.align 2, 0x00
glabel _gTexture7F78B4
.incbin "textures/raw/7F78B4.i4"

.align 2, 0x00
glabel _gTexture7F7934
.incbin "textures/raw/7F7934.i4"

.align 2, 0x00
glabel _gTexture7F79B4
.incbin "textures/raw/7F79B4.i4"

.align 2, 0x00
glabel _gTexture7F7A34
.incbin "textures/raw/7F7A34.i4"

.align 2, 0x00
glabel _gTexture7F7AB4
.incbin "textures/raw/7F7AB4.i4"

.align 2, 0x00
glabel _gTexture7F7B34
.incbin "textures/raw/7F7B34.i4"

.align 2, 0x00
glabel _gTexture7F7BB4
.incbin "textures/raw/7F7BB4.i4"

.align 2, 0x00
glabel _gTexture7F7C34
.incbin "textures/raw/7F7C34.i4"

.align 2, 0x00
glabel _gTexture7F7CB4
.incbin "textures/raw/7F7CB4.i4"

.align 2, 0x00
glabel _gTexture7F7D34
.incbin "textures/raw/7F7D34.i4"

.align 2, 0x00
glabel _gTexture7F7DB4
.incbin "textures/raw/7F7DB4.i4"

.align 2, 0x00
glabel _gTexture7F7E34
.incbin "textures/raw/7F7E34.i4"

.align 2, 0x00
glabel _gTexture7F7EB4
.incbin "textures/raw/7F7EB4.i4"

.align 2, 0x00
glabel _gTexture7F7F34
.incbin "textures/raw/7F7F34.i4"

.align 2, 0x00
glabel _gTexture7F7FB4
.incbin "textures/raw/7F7FB4.i4"

.align 2, 0x00
glabel _gTexture7F8034
.incbin "textures/raw/7F8034.i4"

.align 2, 0x00
glabel _gTexture7F80B4
.incbin "textures/raw/7F80B4.i4"

.align 2, 0x00
glabel _gTexture7F8134
.incbin "textures/raw/7F8134.i4"

.align 2, 0x00
glabel _gTexture7F81B4
.incbin "textures/raw/7F81B4.i4"

.align 2, 0x00
glabel _gTexture7F8234
.incbin "textures/raw/7F8234.i4"

.align 2, 0x00
glabel _gTexture7F82B4
.incbin "textures/raw/7F82B4.i4"

.align 2, 0x00
glabel _gTexture7F8334
.incbin "textures/raw/7F8334.i4"

.align 2, 0x00
glabel _gTexture7F83B4
.incbin "textures/raw/7F83B4.i4"

.align 2, 0x00
glabel _gTexture7F8434
.incbin "textures/raw/7F8434.i4"

.align 2, 0x00
glabel _gTexture7F84B4
.incbin "textures/raw/7F84B4.i4"

.align 2, 0x00
glabel _gTexture7F8534
.incbin "textures/raw/7F8534.i4"

.align 2, 0x00
glabel _gTexture7F85B4
.incbin "textures/raw/7F85B4.i4"

.align 2, 0x00
glabel _gTexture7F8634
.incbin "textures/raw/7F8634.i4"

.align 2, 0x00
glabel _gTexture7F86B4
.incbin "textures/raw/7F86B4.i4"

.align 2, 0x00
glabel _gTexture7F8734
.incbin "textures/raw/7F8734.i4"

.align 2, 0x00
glabel _gTexture7F8914
.incbin "textures/raw/7F8914.i4"

.align 2, 0x00
glabel _gTexture7F8AF4
.incbin "textures/raw/7F8AF4.i4"

.align 2, 0x00
glabel _gTexture7F8CD4
.incbin "textures/raw/7F8CD4.i4"

.align 2, 0x00
glabel _gTexture7F8EB4
.incbin "textures/raw/7F8EB4.i4"

.align 2, 0x00
glabel _gTexture7F9094
.incbin "textures/raw/7F9094.i4"

.align 2, 0x00
glabel _gTexture7F9274
.incbin "textures/raw/7F9274.i4"

.align 2, 0x00
glabel _gTexture7F9454
.incbin "textures/raw/7F9454.i4"

.align 2, 0x00
glabel _gTexture7F9634
.incbin "textures/raw/7F9634.i4"

.align 2, 0x00
glabel _gTexture7F9814
.incbin "textures/raw/7F9814.i4"

.align 2, 0x00
glabel _gTexture7F99F4
.incbin "textures/raw/7F99F4.i4"

.align 2, 0x00
glabel _gTexture7F9A74
.incbin "textures/raw/7F9A74.i4"

.align 2, 0x00
glabel _gTexture7F9AF4
.incbin "textures/raw/7F9AF4.i4"

.align 2, 0x00
glabel _gTexture7F9B74
.incbin "textures/raw/7F9B74.i4"

.align 2, 0x00
glabel _gTexture7F9BF4
.incbin "textures/raw/7F9BF4.i4"

.align 2, 0x00
glabel _gTexture7F9C74
.incbin "textures/raw/7F9C74.i4"

.align 2, 0x00
glabel _gTexture7F9CF4
.incbin "textures/raw/7F9CF4.i4"

.align 2, 0x00
glabel _gTexture7F9DC4
.incbin "textures/raw/7F9DC4.i4"

.align 2, 0x00
glabel _gTexture7F9E44
.incbin "textures/raw/7F9E44.i4"

.align 2, 0x00
glabel _gTexture7F9EC4
.incbin "textures/raw/7F9EC4.i4"

.align 2, 0x00
glabel _gTexture7F9F44
.incbin "textures/raw/7F9F44.i4"

.align 2, 0x00
glabel _gTexture7F9FC4
.incbin "textures/raw/7F9FC4.i4"

.align 2, 0x00
glabel _gTexture7FA044
.incbin "textures/raw/7FA044.i4"

.align 2, 0x00
glabel _gTexture7FA0C4
.incbin "textures/raw/7FA0C4.i4"

.align 2, 0x00
glabel _gTexture7FA194
.incbin "textures/raw/7FA194.i4"

.align 2, 0x00
glabel _gTexture7FA264
.incbin "textures/raw/7FA264.i4"

.align 2, 0x00
glabel _gTexture7FA334
.incbin "textures/raw/7FA334.i4"
.align 0x10,0x00
glabel __textures_0aSegmentEnd
glabel __textures_0aSegmentRomEnd
glabel __textures_0aSegmentSize
.long (__textures_0aSegmentEnd - __textures_0aSegmentStart)

